### ISSUE TITLE
[Missing SNMP Profile]  HP switches

### ISSUE THREAD

**Issue by BalajiTechs** [kentik/snmp-profiles#105]
Below OIDs are HP switches but not being added to snmp_profiles. Can we add them please?

https://oidref.com/1.3.6.1.4.1.11.2.3.7.11

**Comment by Mesverrum** [comment]
@BalajiTechs we merged those sysOID's with our existing HP switch profile, but please pull the new container and try it out in your environment.  I have a suspicion that the .11 HP hardware likely will not actually use the same SNMP OID's as the .25506 H3C hardware.

Easiest test is probably just to see if CPU and memory come through correctly, if they don't we'll ask you to provide a full SNMP walk of one of your switches so we can build a separate profile for the two product lines.  Please let us know how this works out in your environment so we know how it went.

**Comment by BalajiTechs** [comment]
@Mesverrum  I can see the switches correctly added to the group but as you said, Memory and CPU utilization are not coming through. Linking file with full snmpwalk of the switch. Let me know if you need anything else.
[full_snmpwalk.txt](https://github.com/kentik/snmp-profiles/files/7761993/full_snmpwalk.txt)

**Comment by thezackm** [comment]
@BalajiTechs - thanks for this! can you please re-run the walk using the formatting options outlined here?

**SNMP v2c**
```
snmpwalk -v 2c -On -c $COMMUNITY $IP_ADDRESS . >> snmpwalk.txt
```

**SNMP v3**
```
snmpwalk -v 3 -l $LEVEL -u $USERNAME -a $AUTH_PROTOCOL -A $AUTH_PASSPHRASE -x $PRIV_PROTOCOL -X $PRIV_PASSPHRASE -ObentU -Cc $IP_ADDRESS . >> snmpwalk.txt
```

This will output the results into numerical OIDs that we need when analyzing and working with the final results. 

The expected output formatting will look like this
```
.1.3.6.1.4.1.9.9.23.1.1.1.1.2 = INTEGER: 1
```


Thanks!

**Comment by thezackm** [comment]
@BalajiTechs - we were able to pull out the CPU and Memory metrics with PR #112 - once that PR is merged you should be able to pull a new container image and see the results as expected. 

If you are still missing something please provide the SNMP walk, formatted as requested above. Otherwise please let us know if this is working now. Thanks!

**Comment by BalajiTechs** [comment]
@thezackm  Thanks for the quick resolution. I redeployed and now i can see CPU and Memory stats for the HP Switches.

**Comment by thezackm** [comment]
awesome! thanks for the help getting these enabled!
