### ISSUE TITLE
[Missing SNMP Profile] Cisco UCS Manager

### ISSUE THREAD

**Issue by roostergr** [kentik/snmp-profiles#116]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: Cisco

Device Model: UCS Manager version 4.1

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): OID: .1.3.6.1.4.1.9.12.3.1.3.1488

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - CPU, Memory, Bandwidth Usage
 - Traffic and Traffic distribution between interfaces/blades/interconnections 
 - Faults, notifications, CRC errors etc.
 (SNMP info available: ftp://ftp.cisco.com/pub/mibs/supportlists/ucs/ucs-manager-supportlist.html#_Toc303691439)

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link:  https://gist.github.com/roostergr/aefa31e31eab9a86ea13782243a6dfa2

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by thezackm** [comment]
thanks for bringing this device to us @roostergr; unfortunately, the walk you provided is limited and doesn't show the enterprise branch of the MIB tree that would give us more detail about the specific device ([.1.3.6.1.4.1.9.*](http://oid-info.com/get/1.3.6.1.4.1.9)). 

If you can add the vendor-specific portion of the walk that would be ideal; but I think the existing Nexus profile will handle most of the metrics in question. 

Once PR #118 is merged; please [pull a new image and redeploy your container](https://docs.newrelic.com/docs/network-performance-monitoring/advanced/ktranslate-container-management/#updating-the-container) to run a fresh discovery. This should pick up the changes for you.

**Comment by roostergr** [comment]
Hi @thezackm , I have added the snmpwalk from the enterprise branch to the same gist. Thanks for your support.

**Comment by thezackm** [comment]
thanks @roostergr - looking through the results, it looks like we've got it covered in the pending PR; I appreciate the quick help!
