### ISSUE TITLE
Additional MIBs for OpenGear cm41xx devices required

### ISSUE THREAD

**Issue by roostergr** [kentik/snmp-profiles#120]
Hi,
we would like to add the following MIBS to the OpenGear cm41xx devices SNMP profile:
- OG-CONNECT-MIB 
- OG-FAILOVER-MIB 
- OG-SENSOR-MIB 
- OG-SIGNAL-MIB
- OG-STATUS-MIB

Additional information can be found: https://opengear.zendesk.com/hc/en-us/articles/216373103-What-are-the-current-Opengear-MIBs- and also http://ftp.opengear.com/download/snmp/mibs/current/

Thanks

**Comment by thezackm** [comment]
@roostergr - the `OG-STATUS-MIB` was shown in the SNMP walk you originally provided, but it was legacy/deprecated in favor of the `OG-STATUSv2-MIB`, which we used in the resulting profile.

The rest of these MIBs are for SNMP Traps; this is a different process that is a bit more manual for us to build out as you can't run an SNMP walk to capture samples of Trap data.

We can work on getting these added from the vendor MIB files, but it might take a bit. If there is any way for you to trigger these Traps on your CM41xx device(s) and capture them with [tcpdump](https://www.tcpdump.org/) in a `PCAP` for us to review it would be tremendously helpful (but not required).

```
sudo tcpdump -s 0 port 1162 -w opengearTraps.pcap
```

*Changing the port number as needed, `1162` is the default for ktranslate*

**Comment by roostergr** [comment]
@thezackm I will check with the corresponding team and see if it is possible to capture these SNMP traps (maybe a little difficult at the moment since we are in a holiday period). Thanks

**Comment by roostergr** [comment]
@thezackm I checked with the team and at this stage no more information required, so we can close this request. thanks
