### ISSUE TITLE
[Bug] Cisco Nexus profile CPU oid erratic and does not match up to other tools

### ISSUE THREAD

**Issue by Mesverrum** [kentik/snmp-profiles#127]
Currently polling against 1.3.6.1.4.1.9.9.305.1.1.1.0, consensus on various forums and data collected in NR shows this oid is very erratic as it is the point in time value with no time averaging.

Suggesting we remove this from the nexus profiles and fall back to the more typical 1.3.6.1.4.1.9.9.109.1.1.1.1.10

**Comment by thezackm** [comment]
addressed in PR #128
