### ISSUE TITLE
[Bug] NetApp MIBs missing?

### ISSUE THREAD

**Issue by roostergr** [kentik/snmp-profiles#129]
Hi, 

I was wondering if the current MIBs used for NetApp are up to date, since we are missing some metrics. Attaching mib file for you reference:
https://citrix.sharefile.com/d-se58baf0455e94d8183e7c8102054eb94

Thanks

**Comment by Mesverrum** [comment]
Can you be more specific about what additional data you believe should be in the profile?

**Comment by roostergr** [comment]
We have shared the MIBs that are required. You can either check on your side against this or you can let us know what MIBs you are currently supporting so that we can check on our side.

**Comment by roostergr** [comment]
@Mesverrum I am also attaching some missing mibs as example for your reference:
NETAPP-MIB::cDOT*****. e.g. CpuNodeName / cDOTMiscGlobalStatus
NETAPP-MIB::qvStateVolume / qvStateVserver / qvStateName
NETAPP-MIB::dfFileSys / dfKBytesTotal / dfKBytesUsed /dfKBytesAvail / dfStateOnline/ dfVserver/ dfPerCentSaved/ dfLow***
NETAPP-MIB::raidPDiskType/ raidPDiskRPM/ raidPDiskModel
NETAPP-MIB::plexVolName
NETAPP-MIB::enc**** e.g. enclNumberDiskBays/ enclPowerSuppliesFailed/ enclFansMaximum/ enclTempSensorsMaximum/ enclTempSensorsOverTempFail/ enclTempSensorsCurrentTemp/ enclVoltSensorsMaximum/ enclVoltSensorsPresent/ enclVoltSensorsOverVoltFail/ enclVoltSensorsUnderVoltWarnThr/ enclCurSensorsPresent/ :enclCurSensorsOverCurFail/ enclSASConnectPresent/ enclFansSpeed
NETAPP-MIB::ha**** e.g. NodeName/ haState/ haCannotTakeoverCause/ haPartnerStatus/ haPartnerName / haInterconnectStatus.
NETAPP-MIB::netif**** e.g. NETAPP-MIB::netifDescr

There are even more stuff missing. Please let us know if we need to raise a new NetApp profile request and provide snmpwalks and everything...thanks

**Comment by Mesverrum** [comment]
The majority of the oid's you mention are already in there, or they had been deprecated in the mib in favor of others that we already have.  

I added some that weren't there.  Keep in mind that the intention of the snmp profiles in New Relic is to bring in SNMP telemetry primarily around tracking performance issues, it is not intended to be a full snmp inventory of every possible attribute and metadata point.  OID's that can't be mapped back to a performance issue are usually not going to be good to put in the profiles.  That is why we do not just blindly ingest everything in the MIBs.

**Comment by roostergr** [comment]
If the majority of the OIDs are already there, then there is some other issue with NewRelic integration since we do not see these metrics in our profile. Even the default NetApp graphs/queries are not working, so further investigation about all these missing metrics is needed. We will anyway escalate this with a support case.

**Comment by thezackm** [comment]
@roostergr - can you please provide an [SNMP walk](https://docs.newrelic.com/docs/network-performance-monitoring/troubleshooting/snmp-walk#capturing-snmpwalk) for your NetApp so we can validate the metrics it responds to?

**Comment by roostergr** [comment]
@thezackm can i please share it via email just to be on the safe side? thanks

**Comment by roostergr** [comment]
@thezackm btw. for some reason we stopped receiving dfstatus 1.3.6.1.4.1.789.1.5.4.1.20 after pulling the latest image.

**Comment by thezackm** [comment]
> @thezackm can i please share it via email just to be on the safe side? thanks

Surely. I believe you have a support case open, you can share it there and I'll get it.

**Comment by thezackm** [comment]
@roostergr - confirming we got your SNMP walk results; will be reviewing and will report back here with next steps; thanks

**Comment by thezackm** [comment]
@roostergr - looking through your case and logs, we've identified that the current netapp profile has grown larger than the default batch size allowed by the `gosnmp` library. This is why you're suddenly seeing a loss of metrics.

A [feature request](https://github.com/kentik/ktranslate/issues/247) has been opened on the ktranslate repo to provide a work-around for this challenge.

**Comment by roostergr** [comment]
@thezackm great thanks a lot for your support

**Comment by roostergr** [comment]
@thezackm one last thing, does this affect also the nexus-profiles? we lost memoryUtilization metric.
