### ISSUE TITLE
Load Balancers are with "Missing matched profile. See Overview page for details" in newrelic kentik

### ISSUE THREAD

**Issue by HarishankarYellapragada** [kentik/snmp-profiles#14]
Load Balancers (A10) are with snmp v2. 
The devices are identified by the snmp.yaml file but on newrelic they are not projecting any metrics. 
"Missing matched profile. See Overview page for details"

**Comment by thezackm** [comment]
@HarishankarYellapragada - can you please provide the `SysObjectID` for this device?

**Comment by HarishankarYellapragada** [comment]
sysObjectID, Oid: 1.3.6.1.2.1.1.2.0

**Comment by thezackm** [comment]
thanks @HarishankarYellapragada - can you please upload a **SANITIZED** SNMP walk output so we can get this built for you? (It is important to take care and remove any sensitive information please)

An example walk can be seen here; simply replace `$COMMUNITY_STRING` and `$IP_ADDRESS` with your necessary values.
```
snmpwalk -v 2c -On -c $COMMUNITY_STRING $IP_ADDRESS . >> a10_thunder_series_4440s.out
```

**Comment by HarishankarYellapragada** [comment]
Can this issue reopen ?
[a10mib.txt](https://github.com/kentik/snmp-profiles/files/8612855/a10mib.txt)
