### ISSUE TITLE
[Missing SNMP Profile] Netgear M4300-52G Managed Switch missing CPU & Memory usage

### ISSUE THREAD

**Issue by ASchneider-GitHub** [kentik/snmp-profiles#148]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: Netgear

Device Model: M4300-52G

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): .1.3.6.1.4.1.4526.100.1.31

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - CPU usage
 - Memory usage
 - Inbound/Outbound Discards
 - Inbound/Outbound Errors

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: https://gist.github.com/ASchneider-GitHub/89decd674584f836b07a8f59689feb52

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by ASchneider-GitHub** [comment]
It looks like I missed the merge on this one, but it appears the other two missing metrics for the Netgear profile are `Rx Error Rate %` and `Rx Discard Rate %`. The queries powering those charts are below:

**Rx Error Rate %**
```
FROM Metric SELECT round((sum(kentik.snmp.ifInErrors)/sum(kentik.snmp.ifHCInOctets))*100,.01) AS 'Rx Error Rate' WHERE entity.guid = <entityGUID> TIMESERIES FACET if_interface_name OR if_Name SINCE <timestamp> UNTIL <timestamp>
```

**Rx Discard Rate %**
```
FROM Metric SELECT round((sum(kentik.snmp.ifInDiscards)/sum(kentik.snmp.ifHCInOctets))*100,.01) AS 'RX Discard Rate' WHERE entity.guid = <entityGUID> TIMESERIES FACET if_interface_name OR if_Name SINCE <timestamp> UNTIL <timestamp>
```

Are these two metrics going to need their own Issue report with the uploads cloned over to it? Or can this issue be re-opened? @thezackm

**Comment by thezackm** [comment]
```
  - OID: 1.3.6.1.2.1.2.2.1.13
    name: ifInDiscards

  - OID: 1.3.6.1.2.1.2.2.1.14
    name: ifInErrors

  - OID: 1.3.6.1.2.1.31.1.1.1.6
    name: ifHCInOctets

-----
  - OID: 1.3.6.1.2.1.2.2.1.19
    name: ifOutDiscards

  - OID: 1.3.6.1.2.1.2.2.1.20
    name: ifOutErrors

  - OID: 1.3.6.1.2.1.31.1.1.1.10
    name: ifHCOutOctets
```

based on your provided SNMP walk, the device supports all 6 of these OIDs which are used to generate those dashboard widgets; however the Discards and Errors are all 0 (which is a good thing). This is expected behavior on a healthy network.
