### ISSUE TITLE
[Missing SNMP Polling Profile  OpenGear - IM4200]

### ISSUE THREAD

**Issue by araddas** [kentik/snmp-profiles#163]
Device Vendor: OpenGear

Device Model: IM4200

System Object Identifier (SysOID): .1.3.6.1.4.1.25049.1.60

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - CPU
 - Memory
 - Interface (in/out octets)
 - PSU Status
 - Module Status
 - Fan Status
 - Temperature

**FYI The following OIDs have been Sanitized from the Walk**
 - .1.3.6.1.2.1.3.*
 - .1.3.6.1.2.1.4.*
 - .1.3.6.1.2.1.7.*
 - .1.3.6.1.2.1.14.*
 - .1.3.6.1.2.1.197.*

Gist Link: 
https://gist.github.com/araddas/653bf01ab057983160f43c19c736a4f3

**Comment by thezackm** [comment]
@araddas - do you have any information from the vendor on the OIDs for monitoring the primary metrics (CPU/Memory/Interface metrics) for this device? 

The results of the SNMP walk don't show support for collecting any statistics of use for performance monitoring.

**Comment by thezackm** [comment]
details added to Issue #164
