### ISSUE TITLE
[Missing SNMP Polling Profile OpenGear - IM7200]

### ISSUE THREAD

**Issue by araddas** [kentik/snmp-profiles#164]
Device Vendor: OpenGear

Device Model: IM7200

System Object Identifier (SysOID): .1.3.6.1.4.1.25049.1.61

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - CPU
 - Memory
 - Interface (in/out octets)
 - PSU Status
 - Module Status
 - Fan Status
 - Temperature

**FYI The following OIDs have been Sanitized from the Walk**
 - .1.3.6.1.2.1.3.*
 - .1.3.6.1.2.1.4.*
 - .1.3.6.1.2.1.7.*
 - .1.3.6.1.2.1.14.*
 - .1.3.6.1.2.1.197.*

Gist Link: 
https://gist.github.com/araddas/6672aad27f1d8dcf65bdda39491710d1

**Comment by thezackm** [comment]
@araddas - do you have any information from the vendor on the OIDs for monitoring the primary metrics (CPU/Memory/Interface metrics) for this device? 

The results of the SNMP walk don't show support for collecting any statistics of use for performance monitoring.

**Comment by araddas** [comment]
@thezackm the UCS Davis MIB works on these devices for CPU/Memory https://mibs.observium.org/mib/UCD-SNMP-MIB/  (OID 1.3.6.1.4.1.2021) 

Walk for 1.3.6.1.4.1.2021
[ogIM_UCD_Walk.txt](https://github.com/kentik/snmp-profiles/files/8127335/ogIM_UCD_Walk.txt)

**Comment by thezackm** [comment]
thanks @araddas - can you check if they support the [IF-MIB](https://mibs.observium.org/mib/IF-MIB/) as well please? `OID 1.3.6.1.2.1.31.*`

**Comment by araddas** [comment]
@thezackm Yes the IF-MIB works, in addition I found out this is an out of band access device that is basically IP to serial ports. It would be good to get the following oids added as well, its very similar to the if-mib but for serial ports. Also Temp and Humidity sensors.

**Temp/Humidity**
```
Tempurature: 1.3.6.1.4.1.25049.16.4.1.3.1
Humidity: 1.3.6.1.4.1.25049.16.4.1.4.1
```

**Serial Port Table**
```
ogSerialPortStatusTable: 1.3.6.1.4.1.25049.16.1
	ogSerialPortStatusEntry: 1.3.6.1.4.1.25049.16.1.1
		ogSerialPortStatusIndex: 1.3.6.1.4.1.25049.16.1.1.1
		ogSerialPortStatusPort: 1.3.6.1.4.1.25049.16.1.1.2
		ogSerialPortStatusRxBytes: 1.3.6.1.4.1.25049.16.1.1.3
		ogSerialPortStatusTxBytes: 1.3.6.1.4.1.25049.16.1.1.4		
		ogSerialPortStatusSpeed: 1.3.6.1.4.1.25049.16.1.1.5
		ogSerialPortStatusDCD: 1.3.6.1.4.1.25049.16.1.1.6
		ogSerialPortStatusDTR: 1.3.6.1.4.1.25049.16.1.1.7
		ogSerialPortStatusDSR: 1.3.6.1.4.1.25049.16.1.1.8
		ogSerialPortStatusCTS: 1.3.6.1.4.1.25049.16.1.1.9
		ogSerialPortStatusRTS: 1.3.6.1.4.1.25049.16.1.1.10
		ogSerialPortStatusLabel: 1.3.6.1.4.1.25049.16.1.1.11 < Basically ifName ifAlias for serial ports
```
