### ISSUE TITLE
kentik provider master list

### ISSUE THREAD

**Issue by jreardon01** [kentik/snmp-profiles#169]
Hello all - great work here btw :)

Apologies if this is the wrong place for this type of issue, I'm not quite sure who would own this question, whether it be Kentik or New Relic.

Is there a master list of 'provider's that can be used in profiles? Specifically, I'm having a hard time figuring out what kentik-[provider] I would put in a profile.yml file here:
![image](https://user-images.githubusercontent.com/99659318/153915127-8f0969b6-0a6c-4c41-9032-25d51158a285.png)

To specify an environment sensor here:
![image](https://user-images.githubusercontent.com/99659318/153915280-f86b3d99-aa5a-4960-83fe-3e3bf479c133.png)

**Comment by thezackm** [comment]
@jreardon01 - that is somewhat ambiguous and depends on what the ultimate goal is. Realistically, **ktranslate** will send any value you put there, it doesn't really care about that. There is an attempt to set the value dynamically within profiles themselves which helps map the telemetry from a device to the entity UI in New Relic; but that can be overwritten.

The `provider` value is specifically used during entity synthesis on ingest at the New Relic platform, as seen [in our docs](https://docs.newrelic.com/docs/network-performance-monitoring/advanced/advanced-config#devices). The `ENVIRONMENT_SENSOR` entity has 2 current `provider` values supported, which are defined in our [entity-definitions](https://github.com/newrelic/entity-definitions/blob/main/definitions/ext-environment_sensor/definition.yml) repository.

```
provider: kentik-netbotz

provider: kentik-watchdog
```

So essentially, you can set the value of `provider` to anything you want. But in order for you to get an `ENVIRONMENT_SENSOR` entity in New Relic, it needs to be one of these, or you would want to open a PR on this repo adding the profile for your device type to the global list and we would know to get that added to our entity definitions on the back end as part of our normal workflow.

**Comment by jreardon01** [comment]
Hi @thezackm  - I hadn't managed to spot the definitions repository - that's super helpful, thank you :)
