### ISSUE TITLE
[Missing SNMP Profile Request for PowerIQ Devices]

### ISSUE THREAD

**Issue by KarriBharath** [kentik/snmp-profiles#170]
Hi,

We are looking to integrate PowerIQ Devices to New Relic using SNMP Integration. On our PowerIQ we have been configured SNMP V2 configuration.
Unfortunately for PowerIQ devices SNMP-Profiles is missing so we are not getting the metrics into New Relic for monitoring.
So to achieve the customer's goal I would like to request SNMP-Profiles for PowerIQ devices.

I am looking for some basic metrics on those devices below are some of those metrics for their object names.
 
- hrSystem (System Information (e.g., sysUpTime, Number of users, Number of system 
- hrDevice: hrDeviceTable (Device Information (e.g., Device types, Processors, NICs))
- hrDevice: hrProcessorTable (CPU Utilization/Processor Load)
- hrDevice: hrNetworkTable, hrPartitionTable (Network and Partition Table Information)
- hrStorage (Memory and Disk Usage)
- hrSWRun, hwSWRunPerf (Running processes)
- hrSWInstalledTable (Installed software)
- 
....
etc.,

For company security reasons I'm unable to add the output file for SNMPwalk command.

Please let us know if anything needed from us.

Thanks in advance.

Thanks,
Bharath K.

**Comment by thezackm** [comment]
item in queue - SNMP walk results received internally
