### ISSUE TITLE
APC PDU 7800/8800 Temperature and Humidity Sensor OID's missing

### ISSUE THREAD

**Issue by travisroberts-sf** [kentik/snmp-profiles#194]
In working through the migration if our devices into New Relic we are finding that APC PDU Sensor OID's are missing from the profile(s).

Here are the OID's that we are specifically looking for:  
PowerNet-MIB::rPDU2SensorTempHumidityStatusRelativeHumidity
PowerNet-MIB::rPDU2SensorTempHumidityStatusTempF

**Comment by araddas** [comment]
1.3.6.1.4.1.318.1.1.26.10 PowerNet-MIB (rPDU2)

**Comment by thezackm** [comment]
resolved with #196
