### ISSUE TITLE
Cisco IPSLA/RTTR support.

### ISSUE THREAD

**Issue by Thor192** [kentik/snmp-profiles#20]
I don't know if this is the right place to bring this up I don't know if this is a software support issue or a misunderstanding from my perspective on how to use the tool. I'm trying to get data from SNMP involving IPSLA/ RTTR. Is this something that is supported? This is the root OID for CISCO-RTTMON-MIB .1.3.6.1.4.1.9.9.42

**Comment by thezackm** [comment]
@Thor192 - have you been able to test and verify the added OIDs are gathering the data you need?
