### ISSUE TITLE
[Missing SNMP Polling Profile] NetApp H615C

### ISSUE THREAD

**Issue by roostergr** [kentik/snmp-profiles#205]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: NetApp

Device Model: H615C

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): 

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - Performance Metrics
 - Storage/Disk/Volume Metrics
 - Environmental Data

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: https://gist.github.com/roostergr/e016aacd71212d3d209a00aefaaf415c

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by thezackm** [comment]
@roostergr - this device is not showing anything specific to NetApp in its walk; it should be natively polled by the existing [net-snmp.yml](https://github.com/kentik/snmp-profiles/blob/main/profiles/kentik_snmp/_general/net-snmp.yml) profile which would include the `system`, `host-resources` and `ucd` MIBs seen in your walk.

**Comment by thezackm** [comment]
@roostergr - can you provide the sysobjectid for this device please? 

```
snmpwalk -v 2c -On -c $COMMUNITY_STRING $IP_ADDRESS .1.3.6.1.2.1.1.2
```

**Comment by roostergr** [comment]
@thezackm 
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.8072.3.2.10

**Comment by thezackm** [comment]
@roostergr - that's the generic Linux sysOID; can you send me the results of this command? We can try and find a unique identifier to match in the `sysDescr` field.

```
snmpwalk -v 2c -On -c $COMMUNITY_STRING $IP_ADDRESS .1.3.6.1.2.1.1.1
```

**Comment by roostergr** [comment]
@thezackm looks like the identifier will be soldfire8 :)
.1.3.6.1.2.1.1.1.0 = STRING: Linux S04-120 4.19.37-solidfire8 #1 SMP Mon Aug 17 14:34:57 UTC 2020 x86_64
