### ISSUE TITLE
[Missing SNMP Polling Profile] Mellanox SN2700/SN2010

### ISSUE THREAD

**Issue by roostergr** [kentik/snmp-profiles#208]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: Mellanox

Device Model: SN2700/SN2010

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): 

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - Performance Metrics
 - Interface Metrics
 - Traffic/Packets/Bandwidth Metrics
 - Environmental Data

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: https://gist.github.com/roostergr/44214183eb5b179b37b42c3b3d365cf7

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by thezackm** [comment]
@roostergr - can you please confirm the walk on this one? The output has ~10,500 rows, but ends at the `BRIDGE-MIB` with the `.1.3.6.1.2.1.17` root. We'd expect a lot more; the `IF-MIB` root (where all the interface statistics live) is `.1.3.6.1.2.1.31` for instance. 

That's pretty common when a device has a timeout on the walk, you might try again with an additional timeout parameter on the walk command:

```
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out
```

**Comment by roostergr** [comment]
@thezackm sending the new walk on your email :)
