### ISSUE TITLE
kyocera printer [Missing SNMP Polling Profile]

### ISSUE THREAD

**Issue by marvin-hehimself** [kentik/snmp-profiles#214]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: KYOCERA Document Solutions Printing System

Device Model: TASKalfa 3551ci

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): 

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - kcprtAlertTable
 - Hostname, Serial Number, Device Type
 - mailbox/scan-to-mail
 - Errors (no paper)
 - CPU/RAM/key metrics
 - Health status (like the USV)
 - ip adress
 - how many paper is in wich casette
 - how much color is left
 

Example Mib: http://www.oidview.com/mibs/1347/KYOCERA.html

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: https://gist.github.com/marvin-hehimself/aad3ad7145f69b786fd975e4ff46adc6

**Comment by djakobi** [comment]
Hey guys,

thanks a lot for adding the profile for the Kyocera printers. I have replaced the old container with 
a new one together with the NR support team. 

Unfortunately, I can't find the printer in the New Relic Dashboard. Neither as type (NR More > Network > ?) 
nor can I find the device under the name.

However, the log files say that data is being sent to NR. Could you please check the profile again? I suspect 
that here something is not working properly.

If you need support, please contact me.

Best Regards,
Dominik
