### ISSUE TITLE
Local Meraki Mib[Missing SNMP Polling Profile]

### ISSUE THREAD

**Issue by marvin-hehimself** [kentik/snmp-profiles#227]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: Meraki

Device Model: Switch/Access Points

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): 

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - Hostname
 - IP Adresse
 - Device Model / Type
 - as much as possible from v2

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: https://gist.github.com/marvin-hehimself/5ee8807a34e2d9dbf663b26632f61692

Local Meraki Mib: https://documentation.meraki.com/General_Administration/Monitoring_and_Reporting/SNMP_Overview_and_Configuration?msclkid=33f4f928a6ca11ecb0ef9b7819fd000f

Mib Description: https://www.alvestrand.no/objectid/1.3.6.1.2.1.1.html?msclkid=cd923169a6ca11ecbb565da3537fcd47

Meraki devices support the majority of OIDs located within the subset of the following MIBs: 

SNMPv2-MIB .1.3.6.1.2.1.1
IF-MIB .1.3.6.1.2.1
These MIBs are not proprietary and therefore are available on most network monitoring systems.

**Comment by djakobi** [comment]
Hey guys,

thanks a lot for adding the profile for the Meraki devices. I have worked with the NR support team 
to clone the branch locally and mount it in the container so I can test the Meraki MIBS.

In doing so, I noticed the following:
- Our access point is incorrectly displayed as a switch.
- The dashboard for the device is empty.

Obviously only the polling health with the value 1 is transferred here,
the rest is empty. Could you please take a look at this again?

If you have any questions, I can support you.

Best Regards,
Dominik

**Comment by Mesverrum** [comment]
There are a few steps for front end changes that were potentially breaking for users that we had to get through testing before we could clear that part up, it's in progress.  Eventually all meraki devices will just be their own entity class under Network called Meraki Device because the local profile doesn't give anything different for switch/ap/router/firewall/etc, it will all be the same as far as SNMP data goes.  Won't need any changes on your end for that, its all internal for the NR front end.
