### ISSUE TITLE
ILO with ID .1.3.6.1.4.1.232.9.4.10 [Missing SNMP Polling Profile]

### ISSUE THREAD

**Issue by AjeetK** [kentik/snmp-profiles#233]
ILO with ID .1.3.6.1.4.1.232.9.4.10 [Missing SNMP Polling Profile]

[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: HP

Device Model: ILO

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): .1.3.6.1.4.1.232.9.4.10

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - CPU
 - IP
 - Memory
 - Process Count

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link:  https://gist.github.com/AjeetK/0f9437d6405fc1f245bec283c6ec21d9

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by thezackm** [comment]
@AjeetK - this was resolved with PR #244 - you should be good with the latest image now; thanks

**Comment by AjeetK** [comment]
@thezackm I pulled the latest image again and this time its not even showing the uptime, IP and other couple of metrics which it was showing before. In short, no metrics are available now.

**Comment by thezackm** [comment]
can you email me your NR account ID please? I think what's happening is that you used to see a `Kentik Default` entity type and now that we have an SNMP profile for this device we need to build a new entity for it so it shows up in the UI properly. I'll need to look at your data to validate and build the new entity definition.

`zmutchler<at>newrelic.com`

**Comment by AjeetK** [comment]
@thezackm I have shared the account ID over email.
Thanks!

**Comment by AjeetK** [comment]
@thezackm The ILO section is now showing up. Thanks for the release!
The ILO section is showing under "others" tab, instead, it should come under "Network" tab.

Thanks!

**Comment by thezackm** [comment]
We have internal PRs submitted to update the categorization of the ILO entity.
