### ISSUE TITLE
Missing SNMP Polling Profile for Synology DS416j

### ISSUE THREAD

**Issue by mrmichaeladavis** [kentik/snmp-profiles#245]
Device Vendor:  Synology
Device Model: DS416j
System Object Identifier (SysOID): .1.3.6.1.4.1.8072.3.2.10

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - Host
 - Interface
 - Disk

Gist Link: https://gist.github.com/mrmichaeladavis/e42ff1a145abb35c50349c17681edfc3

**Comment by thezackm** [comment]
@mrmichaeladavis - please update the SNMP walk results with the numeric OID format. you can get the proper output with the commands referenced in the issue template.

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```
