### ISSUE TITLE
[Missing SNMP Polling Profile] Multiple Cisco Devices

### ISSUE THREAD

**Issue by hmbasir** [kentik/snmp-profiles#261]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: Cisco Inc.

Device Model: Switch and Router

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)
Please add to the current profile. 
System Object Identifier (SysOID): 

.1.3.6.1.4.1.9.1.1041
.1.3.6.1.4.1.9.1.957
.1.3.6.1.4.1.9.1.525
.1.3.6.1.4.1.9.1.987
.1.3.6.1.4.1.9.1.558
.1.3.6.1.4.1.9.1.1352
.1.3.6.1.4.1.9.1.1353
.1.3.6.1.4.1.9.1.2530
.1.3.6.1.4.1.9.1.963
.1.3.6.1.4.1.9.1.1620
.1.3.6.1.4.1.9.1.1751
.1.3.6.1.4.1.9.1.2961
.1.3.6.1.4.1.9.1.1756
.1.3.6.1.4.1.9.12.3.1.3.1660

**Comment by Mesverrum** [comment]
Hey Husain, 

I was able to get most of those objects rolled in to our existing profiles but there were a few that are new entity types for us that we are going to need you to provide SNMP walks from to be sure we get the profile correct.  If you could get us a full walk from one of each of these device types we can get that done.

.1.3.6.1.4.1.9.12.3.1.3.1660      # Cisco DSC9396 Fiber Channel Switch
.1.3.6.1.4.1.9.1.963      #  Cisco VG204
.1.3.6.1.4.1.9.1.558      #  Cisco VG224

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Links: 
-
-
-


---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```
