### ISSUE TITLE
[Missing SNMP Polling Profile] HP 5406zl

### ISSUE THREAD

**Issue by jplorzano** [kentik/snmp-profiles#268]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: HP ProCurve

Device Model: HP 5406zl

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): .1.3.6.1.4.1.11.2.3.7.11.50

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

- CPU Utilization
- Memory Utilization
- Interface Metrics
- Broadcast Packets
- Multicast Packets

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: 
https://gist.github.com/jplorzano/38dac028c4df50b1304d7aee6331b714
---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by thezackm** [comment]
this device is already covered in [this profile](https://github.com/kentik/snmp-profiles/blob/6a29e92ecf09aa54c96448af17fdb86e15c284f2/profiles/kentik_snmp/aruba/aruba-switch.yml#L62); which will generate a Switch entity in New Relic.

This change was made ~1 week ago in PR #258. Please pull a fresh container image, `docker pull kentik/ktranslate:v2`, and redeploy **ktranslate** to run a discovery job and see the changes in your environment.
