### ISSUE TITLE
[Missing SNMP Polling Profile Device vendor: A10 Thunder, Model: TH4430S]

### ISSUE THREAD

**Issue by HarishankarYellapragada** [kentik/snmp-profiles#291]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: A10 Thunder

Device Model: TH4430S

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): 
OID: .1.3.6.1.4.1.22610.1.3.27

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - Processors
 - Memory
 - Disk
 - Traffic 

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: 

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```
MIB file: 
[a10mib.txt](https://github.com/kentik/snmp-profiles/files/8612913/a10mib.txt)

This issue has been closed due to a delayed response from me https://github.com/kentik/snmp-profiles/issues/14

**Comment by thezackm** [comment]
@HarishankarYellapragada - thanks for the FRs; this issue and your other 2 (#292 and #293) are addressed in PR #296. When that PR is merged, a new container image will be built that will have the changes you need.

Once you pull the latest container image and run a discovery and then run your new polling container, the A10 Thunder devices should automatically associate themselves to the new profile. 

**At that time** please open a ticket with NR Support and reference this issue so we can ensure that your UI experience looks correct and the entities are displaying as expected. (Until you start sending this data to NR, we cannot design the UI experience for them)
