### ISSUE TITLE
Synology NAS DS920+ (DSM 7)

### ISSUE THREAD

**Issue by jbhardman** [kentik/snmp-profiles#297]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: Synology

Device Model: DS920+

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): .1.3.6.1.4.1.8072.3.2.10

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - CPU
 - Memory
 - Network
 - Disk usage (read/writes/storage availability)

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: https://gist.github.com/jbhardman/47343dca5da4160de28d8b106359fe8a

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by jbhardman** [comment]
I ran both types. One with a 30 second timeout, and one starting at the branch recommended:

30 second timeout: 
https://gist.github.com/jbhardman/6de185e755110b91ffe6fc8e7acd33fc

Vendor branch start:
https://gist.github.com/jbhardman/e654db5f7bc84f10f6da3257109b7f72

**Comment by logicbomb421** [comment]
@thezackm thank you for the workaround, that seems to correctly get things organized under a NAS entity in the NR UI.

However, it seems the default overview page isn't finding the expected data:

![Screenshot from 2022-07-22 19-32-40](https://user-images.githubusercontent.com/18082086/180587404-22ddbc55-ec5a-4a5e-8ca9-a3f76a2ef6c2.png)

I have set the following manually in my SNMP config file as described in the workaround:
```yaml
devices:
  ds918__192.168.1.7:
    ...
    mib_profile: "!disk_station.yml"
    provider: kentik-nas
    ...
```

Interestingly, some of the metrics seem to be found when modifying the NRQL query backing the UI widget. For instance, the default query for uptime includes a `WHERE instrumentation.name = 'readynas'` clause that seems to be part of the issue. Changing this to `WHERE instrumentation.name = 'disk_station'` shows the expected data, however, this is not the case for other queries on this page.

For context, I am currently running a DS918+ using DSM 6.2.2. I did notice this issue references DSM 7, so my next step is to perform the upgrade to 7 that I've been putting off, but I wanted to see if this rings any bells.

I should also note that I ran the discovery process before learning about the need to implement this workaround, so my SNMP config file was originally generated from this process if that matters at all. From what I could tell, there isn't any control over the profile usage when running the discovery, but I could be wrong.

Please let me know if I can provide any additional info to assist with troubleshooting. Thanks!

**Comment by thezackm** [comment]
@logicbomb421 -  sorry for the delay as I was on holiday; can you please [DM me directly](https://discuss.newrelic.com/u/zackm) on the Explorer's Hub and share your NR account ID and the email address you use to login with? I need to check your account and build out the UI experience for your new profile. _Alternatively you can open a support case and share the case number with me here if that's easier._
