### ISSUE TITLE
[Missing SNMP Traps Profile] Cisco 3900 router

### ISSUE THREAD

**Issue by hmbasir** [kentik/snmp-profiles#309]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: Cisco 

Device Model: 3900 Routers

**Please attach BOTH a sanitized** *(sensitive information removed)* **PCAP capture of SNMP Trap samples for the device and the MIB file(s) that define the Traps this device will support. Note that the PCAP file will not work as a Gist, it needs to be attached as a file to this issue.**

**The MIB file will give us the enumerated names of the metrics you wish to collect, while the output of the packet capture shows the "true story" of what a device will ship via SNMP Traps and is used to ensure that our profiles are efficient and accurate for your devices.**

**Comment by Mesverrum** [comment]
Hi, 

With this request it looks like you haven't attached the required further information. Are you currently sending these traps into your account that we could work with?
