### ISSUE TITLE
SNMP Walk Results for Brocade Profile ".1.3.6.1.4.1.1588.2.1.1.1.26.1.0 = No Such Instance currently exists at this OID"

### ISSUE THREAD

**Issue by morevillo** [kentik/snmp-profiles#313]
We are currently trying to monitor our Brocade Fibre Channel Switch onto NR. We have done the discovery on our device and came with a matched profile but shows no data coming in (such as CPU and memory).

Further investigation shows (when we did a poll on that device) the following errors as well:
```
2022-05-20T03:31:25.341 ktranslate/poll_now [Warn] KTranslate OID .1.3.6.1.4.1.1588.2.1.1.1.26.1.0 failed to return results, Metric Name: swCpuUsage, Profile: brocade-fc-switch
2022-05-20T03:31:25.341 ktranslate/poll_now [Warn] KTranslate OID .1.3.6.1.4.1.1588.2.1.1.1.26.1.0 failed to return results, Metric Name: swCpuUsage, Profile: brocade-fc-switch
2022-05-20T03:31:25.413 ktranslate/poll_now [Warn] KTranslate OID .1.3.6.1.4.1.1588.2.1.1.1.26.6.0 failed to return results, Metric Name: swMemUsage, Profile: brocade-fc-switch
2022-05-20T03:31:25.413 ktranslate/poll_now [Warn] KTranslate OID .1.3.6.1.4.1.1588.2.1.1.1.26.6.0 failed to return results, Metric Name: swMemUsage, Profile: brocade-fc-switch
```

Also ran an `snmpwalk` against our device with one of the OIDs and showed the following error
```
snmpwalk -v 2c -On -c $COMMUNITY $DEVICE_IP .1.3.6.1.4.1.1588.2.1.1.1.26.1.0
.1.3.6.1.4.1.1588.2.1.1.1.26.1.0 = No Such Instance currently exists at this OID
```

Device details: Brocade BR-6510 16Gb Fibre Channel Switch

**Comment by thezackm** [comment]
Hi @morevillo, thanks for reporting. Please provide a full SNMP walk from your device and we'll start troubleshooting ASAP.

**Comment by morevillo** [comment]
Gist file for output: https://gist.github.com/morevillo/f4789ce45233d7c027733c724348c1d5

**Comment by thezackm** [comment]
@morevillo - that walk looks like it either timed out or the switch doesn't have any support for CPU/Memory metrics.

The last entry is still inside of the global FIBRE-CHANNEL-FE-MIB (`1.3.6.1.2.1.75.*`).

It's expected that the vendor's RESOURCE-MIB ([1.3.6.1.4.1.1588.2.1.1.1.26.*](http://oid-info.com/get/1.3.6.1.4.1.1588.2.1.1.1.26)); which isn't present in your walk results. 

Alternatively, we would expect to see this data in the HOST-RESOURCES-MIB (`1.3.6.1.2.1.25.*`) or even the UCD-SNMP-MIB (`1.3.6.1.4.1.2021.*`); but those are not present either. 

If you can provide the OIDs for CPU and Memory that work for your device we can definitely add them, but the current data is showing no support for these metrics unfortunately.

---
For your reference; these are the MIBs in your results:

SYSTEM-MIB `1.3.6.1.2.1.1.*`
INTERFACES-MIB `1.3.6.1.2.1.2.*`
MIB-2::Address Translation `1.3.6.1.2.1.3.*`
IP-MIB `1.3.6.1.2.1.4.*`
ICMP-MIB `1.3.6.1.2.1.5.*`
TCP-MIB `1.3.6.1.2.1.6.*`
UDP-MIB `1.3.6.1.2.1.7.*`
SNMP-MIB `1.3.6.1.2.1.11.*`
IF-MIB `1.3.6.1.2.1.31.*`
FIBRE-CHANNEL-FE-MIB `1.3.6.1.2.1.75.*`
