### ISSUE TITLE
[Missing SNMP Polling Profile] Servertech Sentry3 PDU

### ISSUE THREAD

**Issue by araddas** [kentik/snmp-profiles#320]
Device Vendor: Servertech

Device Model:  Sentry3 PDU?

System Object Identifier (SysOID): .1.3.6.1.4.1.1718.3

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - Uptime
 - Current/Wattage on a per port basis if possible
 - Power port status
 - Humidity sensor values
 - Model number
 - Serial number

Vendor MIB Download: https://www.servertech.com/support/sentry-mib-oid-tree-downloads

Gist Link: https://gist.github.com/araddas/192f685825655261373657164c054ce5

**Comment by thezackm** [comment]
@araddas  - can you please re-run your SNMP walk with the formatting applied to create numeric output so we can parse the results? 

Instead of this:
```
SNMPv2-MIB::sysDescr.0 = STRING: Sentry Switched PDU
```

We need this:
```
.1.3.6.1.2.1.1.1.0 =  = STRING: Sentry Switched PDU
```

---

```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by araddas** [comment]
@thezackm Updated the gist with the numeric output.

**Comment by araddas** [comment]
@thezackm new gist is here https://gist.github.com/araddas/9f70a1306c1b60304e495adc3bec3d42
