### ISSUE TITLE
[Missing SNMP Polling Profile] ServerTech Sentry4 PDU

### ISSUE THREAD

**Issue by travisroberts-sf** [kentik/snmp-profiles#321]
Device Vendor: ServerTech

Device Model: Sentry4?

System Object Identifier (SysOID): 1.3.6.1.4.1.1718.4

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):
- Uptime
- Current/Wattage on a per port basis if possible
- Power port status
- Humidity sensor values
- Model number
- Serial number

Vendor MIB Download: https://www.servertech.com/support/sentry-mib-oid-tree-downloads

Gist Link:  https://gist.github.com/travisroberts-sf/65e7ddc8db5b3d4af87fd9139c6c7e17

**Comment by thezackm** [comment]
@travisroberts-sf - can you please re-run your SNMP walk with the formatting applied to create numeric output so we can parse the results? 

Instead of this:
```
SNMPv2-MIB::sysDescr.0 = STRING: Sentry Switched PDU
```

We need this:
```
.1.3.6.1.2.1.1.1.0 =  = STRING: Sentry Switched PDU
```

---

```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by travisroberts-sf** [comment]
Sorry about that.  The gist has been updated.

*TRAVIS ROBERTS *

Sr. Site Reliability Engineer | Salesforce

Mobile: 253-290-8477


<https://smart.salesforce.com/sig/travis.roberts//us_mb/default/link.html>
