### ISSUE TITLE
Huawei AR651-X8 and Huawei AC6605 [Missing SNMP Polling Profile]

### ISSUE THREAD

**Issue by guttapavan** [kentik/snmp-profiles#326]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: Huawei AR651-X8, Huawei AC6605

Device Model: AR651_X8-1, AC6605

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): .1.3.6.1.4.1.2011.2.224.279, .1.3.6.1.4.1.2011.2.240.6

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

CPU
Memory
Network
Some thing similar to https://github.com/kentik/snmp-profiles/blob/main/profiles/kentik_snmp/cisco/cisco-all-devices.yml

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: 

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by guttapavan** [comment]
Gistlink: https://gist.github.com/guttapavan/5c306a53898e30916fa5ecf75cd30aa2

**Comment by guttapavan** [comment]
> @guttapavan - **Please provide a [public gist](https://gist.github.com/) with a sanitized** _(sensitive information removed)_ **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**
> 
> Example SNMP walk commands:
> 
> ```
> # v2c example
> snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out
> 
> # v3 example
> snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
> ```



Gistlink: https://gist.github.com/guttapavan/5c306a53898e30916fa5ecf75cd30aa2

**Comment by thezackm** [comment]
@guttapavan - I am not seeing an SNMP walk for the `Huawei AC6605` wireless controller. Can you provide a link for that as well please?

**Comment by guttapavan** [comment]
> @guttapavan - I am not seeing an SNMP walk for the `Huawei AC6605` wireless controller. Can you provide a link for that as well please?
SNMPWalk link:
https://gist.github.com/guttapavan/5c306a53898e30916fa5ecf75cd30aa2

**Comment by thezackm** [comment]
@guttapavan - apologies - I mis-typed earlier - we're missing the walk for the `AR651-X8` router; please provide at your convenience.

**Comment by guttapavan** [comment]
> @guttapavan - apologies - I mis-typed earlier - we're missing the walk for the `AR651-X8` router; please provide at your convenience.
SNMPWALK for AR651-X8
https://gist.github.com/guttapavan/c5f87a09d2e8a0b422b6c8a6b365022b

**Comment by Aldenxu** [comment]
I would like you to re-load snmpwalk for Huawei AR651-X8  because having trouble to get the data. SNMPwalk file is attached
[snmpwalk-X.X.X.101.txt](https://github.com/kentik/snmp-profiles/files/8996685/snmpwalk-X.X.X.101.txt)
[snmpwalk-X.X.X.102.txt](https://github.com/kentik/snmp-profiles/files/8996686/snmpwalk-X.X.X.102.txt)
.
