### ISSUE TITLE
Huawei HUAWEI S6720-54C-EI-48S-AC [Missing SNMP Polling Profile]

### ISSUE THREAD

**Issue by Aldenxu** [kentik/snmp-profiles#327]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: HUAWEI S6720-54C-EI-48S-AC

Device Model: S6720-54C-EI-48S-AC

System Object Identifier (SysOID): .1.3.6.1.4.1.2011.2.23.343

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

CPU
Memory
Network
Some thing similar to https://github.com/kentik/snmp-profiles/blob/main/profiles/kentik_snmp/cisco/cisco-all-devices.yml

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: 

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by thezackm** [comment]
@Aldenxu - **Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by Aldenxu** [comment]
Have uploaded the snmp_walk.out yesterday and any update on it so far?

**Comment by Aldenxu** [comment]
> @Aldenxu - **Please provide a [public gist](https://gist.github.com/) with a sanitized** _(sensitive information removed)_ **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**
> 
> Example SNMP walk commands:
> 
> ```
> # v2c example
> snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out
> 
> # v3 example
> snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
> ```

GistLlink: https://gist.github.com/Aldenxu/9f5d5d1eeb1c4656c54a168cf0627290

**Comment by Aldenxu** [comment]
uploaded gist last week and any update on it so far?

**Comment by thezackm** [comment]
@Aldenxu - confirming that the SNMP walk results look good here and this issue has been placed in our backlog for processing. there is no SLA on these issues but generally speaking we try to complete them within a few weeks time.

**Comment by Aldenxu** [comment]
I would like you to add the file again because only see 5% of the data coming through. SNMPwalk file is attache
[snmpwalk-10.12.1.2.txt](https://github.com/kentik/snmp-profiles/files/8996673/snmpwalk-10.12.1.2.txt)
d
