### ISSUE TITLE
Citrix ADC VPX (1000) [Missing SNMP Polling Profile]

### ISSUE THREAD

**Issue by Aldenxu** [kentik/snmp-profiles#332]
Device Vendor:  Citrix

Device Model: NetScaler Virtual Appliance 450010

System Object Identifier (SysOID): .1.3.6.1.2.1.1.1.0

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - CPU
 -Memory
 -ConcurrentClientNumber
 -Session
 -Everything provided by its SNMP

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: 

---
Example SNMP walk commands:
[snmpwalk_20220426100303-NetScaler.txt](https://github.com/kentik/snmp-profiles/files/8887044/snmpwalk_20220426100303-NetScaler.txt)

# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by Aldenxu** [comment]
Gist Link: https://gist.github.com/Aldenxu/24a3902acc75a6fc7236c521c45dceba

**Comment by thezackm** [comment]
@Aldenxu - this device is already supported in the [netscaler.yml](https://github.com/kentik/snmp-profiles/blob/main/profiles/kentik_snmp/citrix/netscaler.yml) profile. Are there additional metrics not currently in that profile that you need added? If so, please identify their OID(s) and we can review.

**Comment by Aldenxu** [comment]
Hi, Zack,

This is what I am looking for and they are dynamic ones
***@***.***

When You click “value” so you can get more information like this

***@***.***

Not sure how New Relic can display these kinds of data.

Please let me know if you need more information.

Thanks

[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/twg_koru.png]<https://www.twg.co.nz/>
Alden Xu
Chapter Member - Deployment and Automation - SRE and Observability
The Warehouse Group
+6494898900<tel:+6494898900> Ext. 99668
+6421593719<tel:+6421593719>
***@***.*** ***@***.***>
26 The Warehouse Way, Auckland, 0627
PO Box 33470, Takapuna, Auckland, 0740
twg.co.nz<https://www.twg.co.nz>
[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/twl_icon_down_4_group.png]<https://www.thewarehouse.co.nz/>[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/wsl_icon_down_4_group.png]<https://www.warehousestationery.co.nz/>[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/nl_icon_down_4_group.png]<https://www.noelleeming.co.nz/>[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/t7_icon_down_4_group.png]<https://www.torpedo7.co.nz/>[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/1day_icon_down_4_group.png]<https://www.1-day.co.nz/>[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/market_icon_down_4_group.png]<https://www.themarket.com/>

**Comment by thezackm** [comment]
@Aldenxu - the screenshots you sent via email didn't process into the GitHub post; can you login to the GitHub website and add them directly please?

**Comment by Aldenxu** [comment]
Hi, Zack,

I will collect the information asap.

Thanks

Alden

**Comment by Aldenxu** [comment]
Hi, Zack,

Here are the information I need and I might add some more in the future.

================================================================


httpTotGets (1.3.6.1.4.1.5951.4.1.1.48.45)

Total number of HTTP requests received with the GET method.

httpTotPosts (1.3.6.1.4.1.5951.4.1.1.48.46)

Total number of HTTP requests received with the POST method.

httpTotOthers (1.3.6.1.4.1.5951.4.1.1.48.47)

Total number of HTTP requests received with methods other than GET and POST. Some of the other well-defined HTTP methods are HEAD, PUT, DELETE, OPTIONS, and TRACE. User-defined methods are also allowed.

httpTotRxRequestBytes (1.3.6.1.4.1.5951.4.1.1.48.48)

Total number of bytes of HTTP request data received.

httpTotRxResponseBytes (1.3.6.1.4.1.5951.4.1.1.48.49)

Total number of bytes of HTTP response data received.

httpTotTxRequestBytes (1.3.6.1.4.1.5951.4.1.1.48.50)

Total number of bytes of HTTP request data transmitted.

httpTotTxResponseBytes (1.3.6.1.4.1.5951.4.1.1.48.51)

Total number of bytes of HTTP response data transmitted.

httpTot10Requests (1.3.6.1.4.1.5951.4.1.1.48.52)

Total number of HTTP/1.0 requests received.

httpTotResponses (1.3.6.1.4.1.5951.4.1.1.48.53)

Total number of HTTP responses sent.

httpTot10Responses (1.3.6.1.4.1.5951.4.1.1.48.54)

Total number of HTTP/1.0 responses sent.

httpErrIncompleteRequests (1.3.6.1.4.1.5951.4.1.1.48.57)

Total number of HTTP requests received in which the header spans more than one packet.

httpErrIncompleteResponses (1.3.6.1.4.1.5951.4.1.1.48.58)

Total number of HTTP responses received in which the header spans more than one packet.

httpErrIncompleteHeaders (1.3.6.1.4.1.5951.4.1.1.48.60)

Total number of HTTP requests and responses received in which the HTTP header spans more than one packet.

httpErrServerBusy (1.3.6.1.4.1.5951.4.1.1.48.61)

Total number of HTTP error responses received. Some of the error responses are:

500 Internal Server Error

501 Not Implemented

502 Bad Gateway

503 Service Unavailable

504 Gateway Timeout

505 HTTP Version Not Supported

=============================================================

svcTotalClients (1.3.6.1.4.1.5951.4.1.2.1.1.48)

Total number of established client connections.

svcTotalServers (1.3.6.1.4.1.5951.4.1.2.1.1.49)

Total number of established server connections.

================================================================

ifRxAvgBandwidthUsage (1.3.6.1.4.1.5951.4.1.1.54.1.4)

The average bandwidth, in bits per second, at which the specified interface has been receiving packets since the NetScaler appliance was started or the interface statistics were cleared

.1.3.6.1.4.1.5951.4.1.1.54.1.4.3.48.47.49 = GAUGE32: 1648615417

.1.3.6.1.4.1.5951.4.1.1.54.1.4.3.49.47.49 = GAUGE32: 13143759

.1.3.6.1.4.1.5951.4.1.1.54.1.4.3.49.47.50 = GAUGE32: 637581372

.1.3.6.1.4.1.5951.4.1.1.54.1.4.3.49.47.51 = GAUGE32: 160638678

.1.3.6.1.4.1.5951.4.1.1.54.1.4.3.49.47.52 = GAUGE32: 68274936

.1.3.6.1.4.1.5951.4.1.1.54.1.4.4.76.79.47.49 = GAUGE32: 622074992



ifTxAvgBandwidthUsage (1.3.6.1.4.1.5951.4.1.1.54.1.8)

The average bandwidth, in bits per second, at which the specified interface has been transmitting packets since the NetScaler appliance was started or the interface statistics were cleared.

.1.3.6.1.4.1.5951.4.1.1.54.1.8.3.48.47.49 = GAUGE32: 2331802039

.1.3.6.1.4.1.5951.4.1.1.54.1.8.3.49.47.49 = GAUGE32: 13859354

.1.3.6.1.4.1.5951.4.1.1.54.1.8.3.49.47.50 = GAUGE32: 589148504

.1.3.6.1.4.1.5951.4.1.1.54.1.8.3.49.47.51 = GAUGE32: 127060450

.1.3.6.1.4.1.5951.4.1.1.54.1.8.3.49.47.52 = GAUGE32: 44004809

.1.3.6.1.4.1.5951.4.1.1.54.1.8.4.76.79.47.49 = GAUGE32: 835395926

=================================================================

Also tried to use the ones called ifInUtilization, ifOutUtilization, ifInErrorpercent, ifOutErrorPercent don’t get any value. Please advise



Thanks

Alden

[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/twg_koru.png]<https://www.twg.co.nz/>
Alden Xu
Chapter Member - Deployment and Automation - SRE and Observability
The Warehouse Group
+6494898900<tel:+6494898900> Ext. 99668
+6421593719<tel:+6421593719>
***@***.*** ***@***.***>
26 The Warehouse Way, Auckland, 0627
PO Box 33470, Takapuna, Auckland, 0740
twg.co.nz<https://www.twg.co.nz>
[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/twl_icon_down_4_group.png]<https://www.thewarehouse.co.nz/>[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/wsl_icon_down_4_group.png]<https://www.warehousestationery.co.nz/>[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/nl_icon_down_4_group.png]<https://www.noelleeming.co.nz/>[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/t7_icon_down_4_group.png]<https://www.torpedo7.co.nz/>[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/1day_icon_down_4_group.png]<https://www.1-day.co.nz/>[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/market_icon_down_4_group.png]<https://www.themarket.com/>


From: Alden Xu
Sent: Wednesday, 15 June 2022 11:00 AM
To: kentik/snmp-profiles ***@***.***>; kentik/snmp-profiles ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [kentik/snmp-profiles] Citrix ADC VPX (1000) [Missing SNMP Polling Profile] (Issue #332)

Hi, Zack,

I will collect the information asap.

Thanks

Alden

**Comment by Aldenxu** [comment]
what is ETA for this one?

**Comment by Aldenxu** [comment]
Do I need to re-run the snmp polling to be able to get the new data?

**Comment by Mesverrum** [comment]
> Do I need to re-run the snmp polling to be able to get the new data?

You'll need to pull the latest version of the container and it comes with the current profiles.  Just to be sure it's probably a good idea to run a fresh discovery to get any new mibs added into your snmp base yaml.  After the discovery is done your file will be updated and you can stop and remove the old container and run a new instance with the new image and your updated settings.   If you get jammed up on any of it New Relic support can walk you through.

**Comment by Aldenxu** [comment]
I would like you to add whole snmpwalk for this device because missing lots of data. I have attached the whole snmpwalk fil
[snmpwalk-Netscaler.txt](https://github.com/kentik/snmp-profiles/files/8996663/snmpwalk-Netscaler.txt)
e
