### ISSUE TITLE
 Huawei HUAWEI S6720-54C-EI-48S-AC [Missing SNMP Polling Profile]

### ISSUE THREAD

**Issue by Aldenxu** [kentik/snmp-profiles#347]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: Huawei

Device Model: HUAWEI S6720-54C-EI-48S-AC

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): 1.3.6.1.4.1.2011.2.23.343

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - 
 -
 -

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: 

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```
[Huawei Switch snmpwalk-X.X.1.2.txt](https://github.com/kentik/snmp-profiles/files/8998345/Huawei.Switch.snmpwalk-X.X.1.2.txt)

**Comment by Aldenxu** [comment]
You have done this before for us but we can only get 5% of the data and rest of them has nothing even missing match profile error disappeared. please reload this to see.

**Comment by Mesverrum** [comment]
Device included in #341

**Comment by Aldenxu** [comment]
Hi, Marc,

Can I have the device ymal file link created by you please?

Thanks

[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/twg_koru.png]<https://www.twg.co.nz/>
Alden Xu
Chapter Member - Deployment and Automation - SRE and Observability
The Warehouse Group
+6494898900<tel:+6494898900> Ext. 99668
+6421593719<tel:+6421593719>
***@***.*** ***@***.***>
26 The Warehouse Way, Auckland, 0627
PO Box 33470, Takapuna, Auckland, 0740
twg.co.nz<https://www.twg.co.nz>
[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/twl_icon_down_4_group.png]<https://www.thewarehouse.co.nz/>[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/wsl_icon_down_4_group.png]<https://www.warehousestationery.co.nz/>[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/nl_icon_down_4_group.png]<https://www.noelleeming.co.nz/>[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/t7_icon_down_4_group.png]<https://www.torpedo7.co.nz/>[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/1day_icon_down_4_group.png]<https://www.1-day.co.nz/>[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/market_icon_down_4_group.png]<https://www.themarket.com/>

**Comment by Mesverrum** [comment]
https://github.com/kentik/snmp-profiles/blob/main/profiles/kentik_snmp/huawei/huawei-switches.yml

**Comment by Aldenxu** [comment]
Thanks Marc

[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/twg_koru.png]<https://www.twg.co.nz/>
Alden Xu
Chapter Member - Deployment and Automation - SRE and Observability
The Warehouse Group
+6494898900<tel:+6494898900> Ext. 99668
+6421593719<tel:+6421593719>
***@***.*** ***@***.***>
26 The Warehouse Way, Auckland, 0627
PO Box 33470, Takapuna, Auckland, 0740
twg.co.nz<https://www.twg.co.nz>
[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/twl_icon_down_4_group.png]<https://www.thewarehouse.co.nz/>[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/wsl_icon_down_4_group.png]<https://www.warehousestationery.co.nz/>[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/nl_icon_down_4_group.png]<https://www.noelleeming.co.nz/>[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/t7_icon_down_4_group.png]<https://www.torpedo7.co.nz/>[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/1day_icon_down_4_group.png]<https://www.1-day.co.nz/>[https://appsupportstorage.blob.core.windows.net/publicfiles/Signatures/market_icon_down_4_group.png]<https://www.themarket.com/>
