### ISSUE TITLE
[Missing SNMP Polling Profile] - Ubiquity Unifi USG3

### ISSUE THREAD

**Issue by adatole** [kentik/snmp-profiles#387]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: 
Ubiquity

Device Model: 
Unify USG3

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): iso.3.6.1.4.1.41112.1.5

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - CPU
 - RAM
 - any/all interfaces
   - bandwidth
   - errors
   - dropped packets

If there is a New Relic technical support case related to this request, please provide the case number:

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: https://gist.github.com/adatole/178597e3e15b923c329514d6ac4b04da

**Comment by Mesverrum** [comment]
@adatole It looks like this device is already covered by this profile
https://github.com/kentik/snmp-profiles/blob/main/profiles/kentik_snmp/ubiquiti/unifi-security-gateway.yml

Did you try discoverying it with a release of the container image newer than April?

**Comment by adatole** [comment]
> @adatole It looks like this device is already covered by this profile https://github.com/kentik/snmp-profiles/blob/main/profiles/kentik_snmp/ubiquiti/unifi-security-gateway.yml
> 
> Did you try discoverying it with a release of the container image newer than April?

Yes, I just tried discovering it about 20 min ago on a fresh machine. It is discovered, but it only grabs CPU and RAM, not interfaces. I *should* have specified that, so I apologize.

**Comment by Mesverrum** [comment]
This is a New Relic UI issue, not a gap in the profile.  Interface metrics are being collecting, just didn't have a widget on that dashboard to display them.  Will be resolved with upcoming improvements to the firewall dashboards.
