### ISSUE TITLE
Cisco VG224 discovering as Kentik Default

### ISSUE THREAD

**Issue by bradleyk1968** [kentik/snmp-profiles#389]
Device Vendor: Cisco
Device Model: VG224
SolarWinds discovering the device with SYSOBJECTID = 1.3.6.1.4.1.9.1.558

**Comment by bradleyk1968** [comment]
Attached SNMP-WALK.
[SNMP-WALK.log](https://github.com/kentik/snmp-profiles/files/9253366/SNMP-WALK.log)

**Comment by thezackm** [comment]
@bradleyk1968 - please provide an SNMP walk in the format requested in the issue template so we can process the results on our side

thanks

```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by bradleyk1968** [comment]
Yes, pulling that now.

**Comment by bradleyk1968** [comment]
[VG-SNMPWALK.log](https://github.com/kentik/snmp-profiles/files/9410447/VG-SNMPWALK.log)

**Comment by thezackm** [comment]
looks like this one was covered in PR #397
