### ISSUE TITLE
Tripplite UPS Console discovering as Kentik Default

### ISSUE THREAD

**Issue by bradleyk1968** [kentik/snmp-profiles#390]
Device Vendor: TrippUPS

Device Model: SMART500RT1U

SolarWinds discovering using SYSOBJECTID = 1.3.6.1.4.1.850.1.4

**Comment by bradleyk1968** [comment]
Attached SNMP-WALK.
[SNMP-WALK.log](https://github.com/kentik/snmp-profiles/files/9253411/SNMP-WALK.log)

**Comment by thezackm** [comment]
resolved in PR #404
