### ISSUE TITLE
Cisco 3925 router discovering as Kentik Default

### ISSUE THREAD

**Issue by bradleyk1968** [kentik/snmp-profiles#391]
Device Vendor: Cisco Router

Device Model: 3925SPE200

SolarWinds discovering using SYSOBJECTID = 1.3.6.1.4.1.9.1.1144

**Comment by bradleyk1968** [comment]
Attached SNMP-WALK.
[SNMP-WALK.log](https://github.com/kentik/snmp-profiles/files/9253453/SNMP-WALK.log)

**Comment by thezackm** [comment]
this was already addressed in PR #397
