### ISSUE TITLE
Cisco Nexus 7k discovering as Kentik Default

### ISSUE THREAD

**Issue by bradleyk1968** [kentik/snmp-profiles#392]
Device Vendor: Cisco

Device Model: Nexus 7k Series

SolarWinds discovering using SYSOBJECTID = 1.3.6.1.4.1.9.12.3.1.3.612

**Comment by bradleyk1968** [comment]
Attached SNMP-WALK.
[SNMP-WALK.log](https://github.com/kentik/snmp-profiles/files/9253474/SNMP-WALK.log)

**Comment by Mesverrum** [comment]
This sysoid is already in the nexus profile, i double checked your account and right now all the devices with that sysobjectid are mapping correctly to the nexus profile.
https://github.com/kentik/snmp-profiles/blob/ecdfd917701cdc6f68f1720bfb553db07d1667c5/profiles/kentik_snmp/cisco/cisco-nexus.yml#L13
