### ISSUE TITLE
QNAP Turbo NAS TS-1273AU-RP

### ISSUE THREAD

**Issue by DaveSykes2022** [kentik/snmp-profiles#400]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor:  QNAP

Device Model: QNAP Turbo NAS TS-1273AU-RP

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): 1.3.6.1.4.1.24861.2

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - CPU
 - Disk Usage
 - Disk IOPS
 
If there is a New Relic technical support case related to this request, please provide the case number:

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: 

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```
[snmpwalk.txt](https://github.com/kentik/snmp-profiles/files/9308427/snmpwalk.txt)

**Comment by thezackm** [comment]
@DaveSykes2022 - please provide an SNMP walk in the format requested in the issue template so we can process the results on our side

thanks

```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by DaveSykes2022** [comment]
https://gist.github.com/DaveSykes2022/c26f1f8aae48ab9d62fe8ef4b2e559de

**Comment by thezackm** [comment]
@DaveSykes2022 - your results are being shared in the `MIB::OID.Index` default display format:

```
SNMPv2-MIB::sysDescr.0 = STRING: Linux TS-X73AU 4.5.2
```

The command snippet example uses the `-On` (hyphen capital "O" lowercase "n") parameter to format the output into numerical OIDs, identified in the [snmpcmd options](https://linux.die.net/man/1/snmpcmd).

The results should look like this for the same OID above:

```
.1.3.6.1.2.1.1.1.0 = STRING: Linux TS-X73AU 4.5.2
```

This numeric output is necessary for our processing.
