### ISSUE TITLE
[HPVC] Synergy Chassis Virtual Switch

### ISSUE THREAD

**Issue by Mesverrum** [kentik/snmp-profiles#401]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: HP

Device Model: Synergy Virtual Switch

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): 1.3.6.1.2.1.11.5.7.5.9

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - CPU/Mem/Bandwidth
 - Hardware health
 - IF Errors
 - 
 
**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: 

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by viramamur** [comment]
Please find the attached SNMP WALK output.
[RNPSYN102-SNMPWALK.txt](https://github.com/kentik/snmp-profiles/files/9385775/RNPSYN102-SNMPWALK.txt)

**Comment by Mesverrum** [comment]
@viramamur 
I went digging around and was unable to find anywhere with the MIB published for the majority of the OID's in your walk.  In cases like this the vendor will sometimes provide a copy of the MIB file locally on the appliance or through their support portal.  Given that none of the normal sources seems to have it for this device I will need you to provide it from HP so we can build a profile for these device class.
