### ISSUE TITLE
 Ixia Vision xStream 40 (NPB) is showing up as Kentik Default - Can this be categorized as Networking Switch?

### ISSUE THREAD

**Issue by bradleyk1968** [kentik/snmp-profiles#416]
Ixia Vision xStream 40 is a network packet broker (NPB)
Currently discovering as Kentik Default.
Would like this categorized as Ixia Switch or under Switches.
SYSOBJECTID =  1.3.6.1.4.1.23022.100.1.13
That SysID shows the same on NR as it does SW.

![xstream40](https://user-images.githubusercontent.com/68831014/188022688-b11c8742-d324-4b31-9e40-6cdf8c4894c7.JPG)

**Comment by Mesverrum** [comment]
Brad, 

We will need an SNMP Walk from this device to build a profile for Ixia
