### ISSUE TITLE
[Missing SNMP Polling Profile] Dell SonicWALL NSA 4600 #396

### ISSUE THREAD

**Issue by shu-ctc** [kentik/snmp-profiles#422]
Just in case, #396 issue was already closed, so create an this issue. 
Please kindly check the following message.

[Missing SNMP Polling Profile] Dell SonicWALL NSA 4600 #396

------------
Sorry for late reply.
Today, we did destroy current SNMP container and redeploy a fresh container.
(We also check the container image and the update was latest Sep. 9 version)
And also, did the discovery job against the target devices.
However, SNMP container don't recognize Sonicwall profile and still kentik_default.

Is existing sonicwall profile support followings?
Device Model: SonicWALL NSA 4600
System Object Identifier (SysOID): 1.3.6.1.4.1.8741.1
Version: SonicOS Enhanced 6.5.4.6-79n.jpn

Please kindly check the profile again.
------------

**Comment by Mesverrum** [comment]
@shu-ctc the profile already includes the sysOID from your snmp walk.  You will likely need to take this up as a New Relic tech support issue so they can walk through this with you.
