### ISSUE TITLE
Profile Not reporting CPU / Memory - Dell Force10 - S4048T-ON

### ISSUE THREAD

**Issue by TheArchitectIO** [kentik/snmp-profiles#423]
Device Vendor:  Dell
Device Model: S4048T-ON
System Object Identifier (SysOID): .1.3.6.1.4.1.6027.1.3.30

List of critical metrics that you expect in the profile:
 - CPU
 - Memory
 - Network Interfaces

Gist Link: https://gist.github.com/TheArchitectIO/2ac0b696d807ecd130f754453c5db7a7

**Comment by Mesverrum** [comment]
@TheArchitectIO Your snmp walk does not contain any OID's for CPU/Mem.  I suspect you may not have captured the full walk because it looks like your results just cuts off in the middle of a set.  You might try running the walk with a longer timeout by changing the -t 10 to something like -t 30.
