### ISSUE TITLE
[Missing SNMP Polling Profile] PowerConnect 5424

### ISSUE THREAD

**Issue by tiagofavi** [kentik/snmp-profiles#429]
Device Vendor: Dell

Device Model: PowerConnect 5424

System Object Identifier (SysOID): .1.3.6.1.4.1.674.10895.3020

System Object Identifier (SysOID): 

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

How are all metric needs provided that are provided.

But if I need to add something in the future, do I need to open the request in this channel?

 - 
 -
 -
 
If there is a New Relic technical support case related to this request, please provide the case number:

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: 

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by ASchneider-GitHub** [comment]
Customer looking for all available metrics, specifically related to hardware performance.

Case #00056237
