### ISSUE TITLE
[Missing SNMP Profile for Eaton]

### ISSUE THREAD

**Issue by ocastillo88** [kentik/snmp-profiles#44]
Can a profile for Eaton be added?

The MIB file(s) are attached.

```
[eaton-network-connectivity-mib-files.zip](https://github.com/kentik/snmp-profiles/files/7444916/eaton-network-connectivity-mib-files.zip)

**Comment by thezackm** [comment]
we would love to add profile(s) for Eaton equipment @ocastillo88 ; do you have access to any devices to execute an SNMP walk against? It would be very helpful to see what specific OIDs are supported. 

Simply replace `$COMMUNITY` and `$IP_ADDRESS` with the community string and IP address of your device, respectively

```
snmpwalk -v 2c -On -c $COMMUNITY $IP_ADDRESS . >> eaton.out
```

Please sanitize the output for hostnames/ip addresses/etc. and upload to a [public gist](https://gist.github.com/) at your convenience.

**Comment by thezackm** [comment]
validated profile with customer; closing this as resolved
