### ISSUE TITLE
[Missing SNMP Polling Profile]

### ISSUE THREAD

**Issue by tfavi2612br** [kentik/snmp-profiles#444]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor:   OID:.1.3.6.1.4.1.674.10895.3010

Device Model: STRING: "PowerConnect 6224, 3.3.18.1, VxWorks 6.5"

Hello

Follow snmpwalk from switch 6224

I need a profile to be created to implement in new relic.

I need all available metrics.

System Object Identifier (SysOID): 

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - 
 -
 -
 
If there is a New Relic technical support case related to this request, please provide the case number:

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: 

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by Mesverrum** [comment]
@tfavi2612br you did not include an SNMP walk with your issue.  Also, we have already have a profile that includes this model and sysoid
https://github.com/kentik/snmp-profiles/blob/main/profiles/kentik_snmp/dell/dell-powerconnect.yml

When you say you want "all available metrics" that is not going to be able to happen on the public repo.  If you have some specific OIDs that you think would be valuable we can discuss adding them to the profile, but we can't just add everything and call it a day.  Customers of New Relic using these profiles have to pay per GB of data ingested, and collecting a full walk and every possible OID from devices every few minutes generates a huge amount of data that quickly exceeds a reasonable budget for monitoring infra as basic as a switch.  

If you don't mind cranking up the data ingest for your own account you are free to fork the repo and run your own local version where you add all OID's to your local version of the profile, but it would increase the data ingest per switch by at least 100x over what is currently in the profile so I don't recommend it.  We have some docs talking about how we pick what goes into the profiles, and how to run your own local profiles instead
https://docs.newrelic.com/docs/network-performance-monitoring/advanced/snmp-profiles/#oids
