### ISSUE TITLE
[Missing SNMP Polling Profile Linksys SRW2024P ]

### ISSUE THREAD

**Issue by blayjohn33** [kentik/snmp-profiles#450]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: Linksys

Device Model: SRW2024P

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): .1.3.6.1.4.1.3955.6.3.2024.1

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

IP Address
Hostname
Model Information
CPU Usage %
-Uptime
-Interface name
-Interface description
-Vlan interface Bandwidth
[snmpwalk_LinksysSW_JohnBlay.txt](https://github.com/kentik/snmp-profiles/files/9735376/snmpwalk_LinksysSW_JohnBlay.txt)

 
If there is a New Relic technical support case related to this request, please provide the case number: #00056971

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: https://gist.github.com/blayjohn33/116e4380e7a836ec45ae3be35919a5f7

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by thezackm** [comment]
@blayjohn33  - your provided SNMP walk looks to have timed out in the middle of the `POWER-ETHERNET-MIB` 

```
iso.3.6.1.2.1.105.1.4.1.1.2.1 = INTEGER: 1
```

We expect a fully completed walk to have much more information, and the majority of devices will have their most valuable performance metrics in the private side of the MIB tree (`.1.3.6.1.4.*`)

Can you try again and increase the timeout value please?

```
# v2c example
snmpwalk -v 2c -t 30 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 30 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

If that doesn't work, you can try targeting the private MIB space directly:
```
# v2c example
snmpwalk -v 2c -t 30 -On -c $COMMUNITY_STRING $IP_ADDRESS .1.3.6.1.4 >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 30 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS .1.3.6.1.4 >> snmp_walk.out
```

**Comment by blayjohn33** [comment]
> @blayjohn33 - your provided SNMP walk looks to have timed out in the middle of the `POWER-ETHERNET-MIB`
> 
> ```
> iso.3.6.1.2.1.105.1.4.1.1.2.1 = INTEGER: 1
> ```
> 
> We expect a fully completed walk to have much more information, and the majority of devices will have their most valuable performance metrics in the private side of the MIB tree (`.1.3.6.1.4.*`)
> 
> Can you try again and increase the timeout value please?
> 
> ```
> # v2c example
> snmpwalk -v 2c -t 30 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out
> 
> # v3 example
> snmpwalk -v3 -t 30 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
> ```
> 
> If that doesn't work, you can try targeting the private MIB space directly:
> 
> ```
> # v2c example
> snmpwalk -v 2c -t 30 -On -c $COMMUNITY_STRING $IP_ADDRESS .1.3.6.1.4 >> snmp_walk.out
> 
> # v3 example
> snmpwalk -v3 -t 30 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS .1.3.6.1.4 >> snmp_walk.out
> ```

Thanks for your reply, seems all of my Linksys switches end here during the snmp walk for both public and private. What can be created with the current data?

**Comment by Mesverrum** [comment]
from the profile:
No CPU or memory OID appears to be available for this product line, this profile just collects interface data and moves the linksys devices to the switch category
