### ISSUE TITLE
[Missing SNMP Polling Profile] Eaton ePDU G3

### ISSUE THREAD

**Issue by gridless-compute** [kentik/snmp-profiles#452]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor:  Eaton

Device Model: ePDU G3

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): 1.3.6.1.4.1.534.6.6.7

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

notifications, inputs, outlets, environmental, temperature, humidity, 
 - 
 -
 -
 
If there is a New Relic technical support case related to this request, please provide the case number:

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: https://gist.github.com/gridless-compute/811647a6a8ed88d094b4e63f959a8e42

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by thezackm** [comment]
@gridless-compute - you've annotated that you would like `notifications` added to the profile for this device series. Can you please open a new issue for [SNMP Traps Profile Request](https://github.com/kentik/snmp-profiles/issues/new?assignees=&labels=snmp-trap-profile&template=snmp-traps-profile-request.md&title=%5BMissing+SNMP+Traps+Profile%5D) and provide the requested MIB file that outlines the traps this device supports as well as a `.pcap` file of sample traps so we can model that part of the profile correctly?

We will work on the SNMP polling portion on this issue as we get to it in our backlog. Thank you.
