### ISSUE TITLE
[Missing SNMP Polling Profile Dell PowerConnect 5424]

### ISSUE THREAD

**Issue by blayjohn33** [kentik/snmp-profiles#453]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: Dell 
Device Model: PowerConnect 5424

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): 
3.6.1.4.1.674.10895.3020

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

IP
Hostname
Model Info
Uptime
CPU Util %
Memory Util %
Interface name
Interface description
Interface status
Vlan Interface bandwidth Util
 
If there is a New Relic technical support case related to this request, please provide the case number:

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link:  https://gist.github.com/blayjohn33/733603c754f7c5cea980101c6d2f467c
---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by thezackm** [comment]
@blayjohn33 - your provided SNMP walk looks to have timed out in the middle of the `DISMAN-TRACEROUTE-MIB` 

```
iso.3.6.1.2.1.81.1.1.0 = Gauge32: 10
```

We expect a fully completed walk to have much more information, and the majority of devices will have their most valuable performance metrics in the private side of the MIB tree (`.1.3.6.1.4.*`)

Can you try again and increase the timeout value please?

```
# v2c example
snmpwalk -v 2c -t 30 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 30 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

If that doesn't work, you can try targeting the private MIB space directly:
```
# v2c example
snmpwalk -v 2c -t 30 -On -c $COMMUNITY_STRING $IP_ADDRESS .1.3.6.1.4 >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 30 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS .1.3.6.1.4 >> snmp_walk.out
```

**Comment by blayjohn33** [comment]
> @blayjohn33 - your provided SNMP walk looks to have timed out in the middle of the `DISMAN-TRACEROUTE-MIB`
> 
> ```
> iso.3.6.1.2.1.81.1.1.0 = Gauge32: 10
> ```
> 
> We expect a fully completed walk to have much more information, and the majority of devices will have their most valuable performance metrics in the private side of the MIB tree (`.1.3.6.1.4.*`)
> 
> Can you try again and increase the timeout value please?
> 
> ```
> # v2c example
> snmpwalk -v 2c -t 30 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out
> 
> # v3 example
> snmpwalk -v3 -t 30 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
> ```
> 
> If that doesn't work, you can try targeting the private MIB space directly:
> 
> ```
> # v2c example
> snmpwalk -v 2c -t 30 -On -c $COMMUNITY_STRING $IP_ADDRESS .1.3.6.1.4 >> snmp_walk.out
> 
> # v3 example
> snmpwalk -v3 -t 30 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS .1.3.6.1.4 >> snmp_walk.out
> ```

Hi, Thanks for the replay. I targeted both public and private and it always seems to end in the same section. I tried the walk on another powerconnect switch at: [https://gist.github.com/blayjohn33/8232e954891404534d2c4d9ca06b1039]

**Comment by blayjohn33** [comment]
@thezackm Hi, Thanks for the replay. I targeted both public and private and it always seems to end in the same section. I tried the walk on another powerconnect switch at: [https://gist.github.com/blayjohn33/8232e954891404534d2c4d9ca06b1039]
