### ISSUE TITLE
[Missing SNMP Polling Profile] Open Gear CM7148

### ISSUE THREAD

**Issue by jackson-thomas-bfg** [kentik/snmp-profiles#468]
Device Vendor: Open Gear

Device Model: CM7148-2-DAC

System Object Identifier (SysOID): .1.3.6.1.4.1.25049.1.11

Gist Link: https://gist.github.com/jackson-thomas-bfg/297678024112b8437961930cbd3c1064

This should be similar to https://github.com/kentik/snmp-profiles/blob/117c6a271a9a608180b58ed637a8cf04f4c0fea2/profiles/kentik_snmp/opengear/opengear-console-manager.yml , likely just needs the sys id added for the CM 7XXX series, as the one provided is only for the CM 4XXX series

**Comment by Mesverrum** [comment]
Closed by #471
