### ISSUE TITLE
[Missing SNMP Profile] Netgear ProSafe M4300-52G

### ISSUE THREAD

**Issue by ahill-itim** [kentik/snmp-profiles#47]
Device Vendor: Netgear

Device Model: ProSafe M4300-52G

System Object Identifier (SysOID): .1.3.6.1.4.1.4526.100.1.31

List of MIBs expected: 

RFC 1907 - SNMPv2-MIB | The MIB module for SNMPv2 entities
HC-RMON-MIB | The original version of this MIB, published as RFC3273.
HCNUM-TC | A MIB module containing textual conventions for high capacity data types.
SNMP-COMMUNITY-MIB | This MIB module defines objects to help support coexistence between SNMPv1, SNMPv2, and SNMPv3.
SNMP-MPD-MIB | The MIB for Message Processing and Dispatching
SNMP-TARGET-MIB | The Target MIB Module
SNMP-VIEW-BASED-ACM-MIB | The management information definitions for the View-based Access Control Model for SNMP.
NETGEAR-POWER-ETHERNET-MIB | NETGEAR Power Ethernet Extensions MIB
SFLOW-MIB | sFlow MIB
NETGEAR-ISDP-MIB | Industry Standard Discovery Protocol MIB
NETGEAR-BOXSERVICES-PRIVATE-MIB | The NETGEAR Private MIB for NETGEAR Box Services Feature.
IANA-ADDRESS-FAMILY-NUMBERS-MIB | The MIB module defines the AddressFamilyNumbers textual convention.
NETGEAR-DHCPCLIENT-PRIVATE-MIB | The NETGEAR Private MIB for NETGEAR DHCP Client
NETGEAR-DENIALOFSERVICE-PRIVATE-MIB | The NETGEAR Private MIB for NETGEAR Denial of Service.
NETGEAR-KEYING-PRIVATE-MIB | The NETGEAR Private MIB for NETGEAR Keying Utility
LLDP-EXT-DOT3-MIB | The LLDP Management Information Base extension module for IEEE 802.3 organizationally defined discovery information.
NETGEAR-LLPF-PRIVATE-MIB | The NETGEAR Private MIB for NETGEAR Link Local Protocol Filtering.
DISMAN-PING-MIB | The Ping MIB (DISMAN-PING-MIB) provides the capability of controlling the use of the ping function at a remote host.
DNS-RESOLVER-MIB | The MIB module for entities implementing the client (resolver) side of the Domain Name System (DNS) protocol.
NETGEAR-OUTBOUNDTELNET-PRIVATE-MIB | The NETGEAR Private MIB for NETGEAR Outbound Telnet
NETGEAR-TIMEZONE-PRIVATE-MIB | The NETGEAR Private MIB for NETGEAR for system time, timezone and summer-time settings
LAG-MIB | The Link Aggregation module for managing IEEE 802.3ad
RFC 1493 - BRIDGE-MIB | Definitions of Managed Objects for Bridges (dot1d)
RFC 2674 - Q-BRIDGE-MIB | The VLAN Bridge MIB module for managing Virtual Bridged Local Area Networks
RFC 2863 - IF-MIB | The Interfaces Group MIB using SMIv2
NETGEAR-SWITCHING-MIB | NETGEAR Switching - Layer 2
NETGEAR-PORTSECURITY-PRIVATE-MIB | Port Security MIB.
IANAifType-MIB | This MIB module defines the IANAifType Textual Convention
MAU-MIB | Management information for 802.3 MAUs.
NETGEAR-MVR-PRIVATE-MIB | The NETGEAR Private MIB for MVR Configuration
IEEE8021-PFC-MIB | Priority-based Flow Control module for managing IEEE 802.1Qbb
IEEE8021-PAE-MIB | Port Access Entity module for managing IEEE 802.1X.
NETGEAR-DOT1X-AUTHENTICATION-SERVER-MIB | The NETGEAR Private MIB for NETGEAR Dot1x Authentication Server
RADIUS-ACC-CLIENT-MIB | RADIUS Accounting Client MIB
TACACS-CLIENT-MIB | Defines a portion of the SNMP MIB under the NETGEAR Corporation enterprise OID pertaining to TACACS+ client configuration.
NETGEAR-AUTHENTICATION-MANAGER-MIB | The NETGEAR Private MIB for NETGEAR authentication manager feature.
RFC 1724 - RIPv2-MIB | RIP Version 2 MIB Extension
RFC 1850 - OSPF-TRAP-MIB | The MIB module to describe traps for the OSPF Version 2 Protocol.
NETGEAR-ROUTING-MIB | NETGEAR Routing - Layer 3
IP-MIB | The MIB module for managing IP and ICMP implementations, but excluding their management of IP routes.
NETGEAR-QOS-MIB | NETGEAR Flex QOS Support
NETGEAR-QOS-COS-MIB | NETGEAR Flex QOS COS
RFC 3289 - DIFFSERV-DSCP-TC | Management Information Base for the Textual Conventions used in DIFFSERV-MIB
NETGEAR-QOS-DIFFSERV-EXTENSIONS-MIB | NETGEAR Flex QOS DiffServ Private MIBs' definitions
NETGEAR-QOS-ISCSI-MIB | NETGEAR Flex QOS iSCSI Flow Acceleration MIBs' definitions
draft-ietf-magma-mgmd-mib-03 | MGMD MIB, includes IGMPv3 and MLDv2.
RFC 5240 - PIM-BSR-MIB | Bootstrap Router mechanism for PIM routers
IANA-RTPROTO-MIB | IANA IP Route Protocol and IP MRoute Protocol Textual Conventions
IPMROUTE-STD-MIB | The MIB module for management of IP Multicast routing, but independent of the specific multicast routing protocol in use.
NETGEAR-NSF-MIB | The MIB module defines objects to configure Non Stop Forwarding.
RFC 2466 - IPV6-ICMP-MIB | Management Information Base for IP Version 6: ICMPv6 Group
NETGEAR-ROUTING6-MIB | The NETGEAR Private MIB for NETGEAR IPv6 Routing.
NETGEAR-IPV6-LOOPBACK-MIB | The NETGEAR Private MIB for NETGEAR Loopback IPV6 address configuration.

**If possible, please add a current SNMP walk of the device, with sensitive information removed**

```
# v2c example
snmpwalk -v 2c -On -c $COMMUNITY_STRING $IP_ADDRESS . >> $DEVICE_TYPE.out

# v3 example
snmpwalk -v3 -On -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS $IP_ADDRESS . >> $DEVICE_TYPE.out
```

**Comment by thezackm** [comment]
@ahill-itim - please provide a [public gist](https://gist.github.com/) with a sanitized SNMP walk of the device and we will get this in queue. We need a more targeted list of metrics than the generic list of every MIB the device supports please.
