### ISSUE TITLE
[Missing SNMP Polling Profile] NEC IX2207

### ISSUE THREAD

**Issue by zyun-i** [kentik/snmp-profiles#470]
Device Vendor: NEC

Device Model: IX2207

System Object Identifier (SysOID): .1.3.6.1.4.1.119.1.84.18.1

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

- Interface utilization
- SYSTEM MIB https://jpn.nec.com/univerge/ix/Manual/MIB/PICO-SMI-MIB.txt
  - temperature
  - voltage
  - CPU utilization
  - Memory utilization
 
If there is a New Relic technical support case related to this request, please provide the case number: None

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: https://gist.github.com/zyun-i/63b24e9c113464f5851f9d0887b3fc40

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by Mesverrum** [comment]
Resolved with #489
