### ISSUE TITLE
[Missing SNMP Polling Profile]

### ISSUE THREAD

**Issue by EstebanCM** [kentik/snmp-profiles#472]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: Brocade

Device Model: 5470

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): 1.3.6.1.4.1.1588.2.1.3

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - 
 -
 -
 
If there is a New Relic technical support case related to this request, please provide the case number:

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: 
https://gist.github.com/EstebanCM/7228c26f7acf51582f07d72487be4c04
---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by IrAriasKC** [comment]
Hi @thezackm  & @Mesverrum ,

Thou we have updated our container to the latest version released 9 days ago (docker pull kentik/ktranslate:v2) our Brocade 5470 devices are still being discovered as kentik-default with base MIBs. 

Can we get this issue re-open?

- Device 5470 discovered as kentik-default 

![image](https://user-images.githubusercontent.com/95935176/213301994-83732040-ac63-4e48-bdad-ebbda0da30f6.png)

- ktranslate Image digests
![image](https://user-images.githubusercontent.com/95935176/213303240-54cce7dc-fb7e-401a-af5f-a15e601ae8d1.png)
