### ISSUE TITLE
[Missing SNMP Polling Profile] Avocent ACS 8000 Console Server

### ISSUE THREAD

**Issue by jlrgraham23** [kentik/snmp-profiles#476]
Device Vendor: Avocent

Device Model: ACS 8000

System Object Identifier (SysOID): `.1.3.6.1.4.1.10418.26.1.2`

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - Device shows in New Relic as using a generic profile.
 
If there is a New Relic technical support case related to this request, please provide the case number: 00075880

**Comment by Mesverrum** [comment]
@jlrgraham23 You did not attach an SNMP walk to this issue or send one as part of the GTS case. Without those walks we cannot build a profile.

If you can attach a gist of a walk we can get started on building a profile.

**Comment by jlrgraham23** [comment]
Hi @Mesverrum, the file was uploaded as `Avocent-ACS-8000.out`.  If I need to re-upload these can you have our support engineer provide an upload link again to make sure we're all on the same page?

**Comment by jlrgraham23** [comment]
During our support session these were requested as uploads to a `newrelic.sharefile.com` site, if that makes any difference.

**Comment by ASchneider-GitHub** [comment]
Please note that `snmpwalk` output files have been transferred from ShareFile to Case #00075880.

**Comment by Mesverrum** [comment]
Resolved via #491
