### ISSUE TITLE
[Missing SNMP Polling Profile] EMC Data Domain DD22500

### ISSUE THREAD

**Issue by AselaP** [kentik/snmp-profiles#480]
- Device Vendor: EMC Data Domain
- Device Model: DD22500
- System Object Identifier: .1.3.6.1.4.1.19746.3.1.36
- Critical Metrics:
- Gist Link: snmpwalk can be found attached to support case 00069985

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): 

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):
- free space, utilized space, errors, warnings, critical errors,
- This is a storage device.
 
If there is a New Relic technical support case related to this request, please provide the case number: 00069985 

- Gist Link: snmpwalk can be found attached to support case 00069985

**Comment by Mesverrum** [comment]
Resolved by #514
