### ISSUE TITLE
[Missing SNMP Polling Profile]  Cisco C1905 Integrated Services Router

### ISSUE THREAD

**Issue by afidelispp** [kentik/snmp-profiles#485]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: Cisco

Device Model: C1905/K9 Integrated Services Router

System Object Identifier (SysOID): .1.3.6.1.4.1.9.1.1192
 
If there is a New Relic technical support case related to this request, please provide the case number: #00080223

It is already in CISCO-PRODUCTS-MIB

**Comment by nr-dlaturner** [comment]
I'll take a look at this one.

**Comment by nr-dlaturner** [comment]
Resolved.  Added 190ISR OID  - https://github.com/kentik/snmp-profiles/pull/493
