### ISSUE TITLE
[Missing SNMP Profile] Juniper SRX340

### ISSUE THREAD

**Issue by ahill-itim** [kentik/snmp-profiles#49]
Device Vendor: Juniper

Device Model: SRX340

System Object Identifier (SysOID): .1.3.6.1.4.1.2636.1.1.1.2.135

List of MIBs expected: 

There is a downloadable full list here:

https://apps.juniper.net/mib-explorer/download.jsp#product=Junos%20OS

Let me know if you need more info.

**If possible, please add a current SNMP walk of the device, with sensitive information removed**

```
# v2c example
snmpwalk -v 2c -On -c $COMMUNITY_STRING $IP_ADDRESS . >> $DEVICE_TYPE.out

# v3 example
snmpwalk -v3 -On -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS $IP_ADDRESS . >> $DEVICE_TYPE.out
```

**Comment by thezackm** [comment]
This is a currently supported device

[profile link](https://github.com/kentik/snmp-profiles/blob/b63f13ff9d96671d102abd8546552f9205cb9d08/profiles/kentik_snmp/juniper/juniper-srx-firewalls.yml#L40)
