### ISSUE TITLE
[Missing SNMP Polling Profile] - AVTECTH

### ISSUE THREAD

**Issue by viramamur** [kentik/snmp-profiles#495]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor:  AVTECH

Device Model: RA3S-70234E

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): 

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - 
 -
 -
 
If there is a New Relic technical support case related to this request, please provide the case number:

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link:   https://avtech.com/articles/8268/find-snmp-values-room-alert-sensors/ 

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by viramamur** [comment]
<html>
<body>


avtech |   | .1.3.6.1.4.1.20916
-- | -- | --
products |   | .1.3.6.1.4.1.20916.1
roomalert3S |   | .1.3.6.1.4.1.20916.1.13
sensors |   | .1.3.6.1.4.1.20916.1.13.1
internal |   | .1.3.6.1.4.1.20916.1.13.1.1
temperature |   | .1.3.6.1.4.1.20916.1.13.1.1.1
internal-tempf | mandatory | .1.3.6.1.4.1.20916.1.13.1.1.1.1
internal-tempc | mandatory | .1.3.6.1.4.1.20916.1.13.1.1.1.2
digital |   | .1.3.6.1.4.1.20916.1.13.1.2
digital-sen1 |   | .1.3.6.1.4.1.20916.1.13.1.2.1
digital-sen1-1 | mandatory | .1.3.6.1.4.1.20916.1.13.1.2.1.1
digital-sen1-2 | mandatory | .1.3.6.1.4.1.20916.1.13.1.2.1.2
digital-sen1-3 | mandatory | .1.3.6.1.4.1.20916.1.13.1.2.1.3
digital-sen1-4 | mandatory | .1.3.6.1.4.1.20916.1.13.1.2.1.4
digital-sen1-5 | mandatory | .1.3.6.1.4.1.20916.1.13.1.2.1.5
digital-sen1-6 | mandatory | .1.3.6.1.4.1.20916.1.13.1.2.1.6
digital-sen1-7 | mandatory | .1.3.6.1.4.1.20916.1.13.1.2.1.7
switch |   | .1.3.6.1.4.1.20916.1.13.1.3
switch-sen1 | mandatory | .1.3.6.1.4.1.20916.1.13.1.3.1
traps |   | .1.3.6.1.4.1.20916.1.13.2
alarmmessage | mandatory | .1.3.6.1.4.1.20916.1.13.2.1
externalrelays |   | .1.3.6.1.4.1.20916.1.13.3
externalrelay1 |   | .1.3.6.1.4.1.20916.1.13.3.1
externalrelay1-element-one | mandatory | .1.3.6.1.4.1.20916.1.13.3.1.1
externalrelay1-element-two | mandatory | .1.3.6.1.4.1.20916.1.13.3.1.2
externalrelay1-element-three | mandatory | .1.3.6.1.4.1.20916.1.13.3.1.3
externalrelay1-element-four | mandatory | .1.3.6.1.4.1.20916.1.13.3.1.4
externalrelay1-element-five | mandatory | .1.3.6.1.4.1.20916.1.13.3.1.5
externalrelay1-element-six | mandatory | .1.3.6.1.4.1.20916.1.13.3.1.6
externalrelay1-element-seven | mandatory | .1.3.6.1.4.1.20916.1.13.3.1.7
externalrelay1-element-eight | mandatory | .1.3.6.1.4.1.20916.1.13.3.1.8


</body>
</html>[avtech](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#avtech)		.1.3.6.1.4.1.20916
 [products](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#products)		.1.3.6.1.4.1.20916.1
 [roomalert3S](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#roomalert3S)		.1.3.6.1.4.1.20916.1.13
 [sensors](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#sensors)		.1.3.6.1.4.1.20916.1.13.1
 [internal](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#internal)		.1.3.6.1.4.1.20916.1.13.1.1
 [temperature](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#temperature)		.1.3.6.1.4.1.20916.1.13.1.1.1
 [internal-tempf ](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#internal-tempf)	mandatory	.1.3.6.1.4.1.20916.1.13.1.1.1.1
 [internal-tempc ](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#internal-tempc)	mandatory	.1.3.6.1.4.1.20916.1.13.1.1.1.2
 [digital](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#digital)		.1.3.6.1.4.1.20916.1.13.1.2
 [digital-sen1](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#digital-sen1)		.1.3.6.1.4.1.20916.1.13.1.2.1
 [digital-sen1-1 ](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#digital-sen1-1)	mandatory	.1.3.6.1.4.1.20916.1.13.1.2.1.1
 [digital-sen1-2 ](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#digital-sen1-2)	mandatory	.1.3.6.1.4.1.20916.1.13.1.2.1.2
 [digital-sen1-3 ](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#digital-sen1-3)	mandatory	.1.3.6.1.4.1.20916.1.13.1.2.1.3
 [digital-sen1-4 ](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#digital-sen1-4)	mandatory	.1.3.6.1.4.1.20916.1.13.1.2.1.4
 [digital-sen1-5 ](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#digital-sen1-5)	mandatory	.1.3.6.1.4.1.20916.1.13.1.2.1.5
 [digital-sen1-6 ](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#digital-sen1-6)	mandatory	.1.3.6.1.4.1.20916.1.13.1.2.1.6
 [digital-sen1-7 ](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#digital-sen1-7)	mandatory	.1.3.6.1.4.1.20916.1.13.1.2.1.7
 [switch](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#switch)		.1.3.6.1.4.1.20916.1.13.1.3
 [switch-sen1 ](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#switch-sen1)	mandatory	.1.3.6.1.4.1.20916.1.13.1.3.1
 [traps](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#traps)		.1.3.6.1.4.1.20916.1.13.2
 [alarmmessage ](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#alarmmessage)	mandatory	.1.3.6.1.4.1.20916.1.13.2.1
 [externalrelays](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#externalrelays)		.1.3.6.1.4.1.20916.1.13.3
 [externalrelay1](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#externalrelay1)		.1.3.6.1.4.1.20916.1.13.3.1
 [externalrelay1-element-one ](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#externalrelay1-element-one)	mandatory	.1.3.6.1.4.1.20916.1.13.3.1.1
 [externalrelay1-element-two ](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#externalrelay1-element-two)	mandatory	.1.3.6.1.4.1.20916.1.13.3.1.2
 [externalrelay1-element-three ](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#externalrelay1-element-three)	mandatory	.1.3.6.1.4.1.20916.1.13.3.1.3
 [externalrelay1-element-four ](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#externalrelay1-element-four)	mandatory	.1.3.6.1.4.1.20916.1.13.3.1.4
 [externalrelay1-element-five ](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#externalrelay1-element-five)	mandatory	.1.3.6.1.4.1.20916.1.13.3.1.5
 [externalrelay1-element-six ](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#externalrelay1-element-six)	mandatory	.1.3.6.1.4.1.20916.1.13.3.1.6
 [externalrelay1-element-seven ](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#externalrelay1-element-seven)	mandatory	.1.3.6.1.4.1.20916.1.13.3.1.7
 [externalrelay1-element-eight ](https://mibs.observium.org/mib/ROOMALERT3S-MIB/#externalrelay1-element-eight)	mandatory	.1.3.6.1.4.1.20916.1.13.3.1.8

**Comment by viramamur** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/VIRAMA~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/VIRAMA~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Column1 | Column2 | Column3 | Column4 | Column5 | Column6 | Column7 | Column8 | Column9 | Column10 | Column11 | Column12
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Name | Full Name | OID | Type | Access | Indexes | MIB Module | Description |   |   |   |  
avtech | .iso.org.dod.internet.private.enterprises.avtech | .1.3.6.1.4.1.20916 |   |   |   | ROOMALERT3S-MIB |   |   |   |   |  
products | .iso.org.dod.internet.private.enterprises.avtech.products | .1.3.6.1.4.1.20916.1 |   |   |   | ROOMALERT3S-MIB |   |   |   |   |  
roomalert3S | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S | .1.3.6.1.4.1.20916.1.13 |   |   |   | ROOMALERT3S-MIB |   |   |   |   |  
sensors | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.sensors | .1.3.6.1.4.1.20916.1.13.1 |   |   |   | ROOMALERT3S-MIB |   |   |   |   |  
internal | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.sensors.internal | .1.3.6.1.4.1.20916.1.13.1.1 |   |   |   | ROOMALERT3S-MIB |   |   |   |   |  
temperature | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.sensors.internal.temperature | .1.3.6.1.4.1.20916.1.13.1.1.1 |   |   |   | ROOMALERT3S-MIB |   |   |   |   |  
internal-tempf | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.sensors.internal.temperature.internal-tempf | .1.3.6.1.4.1.20916.1.13.1.1.1.1 | INTEGER | read-only |   | ROOMALERT3S-MIB | The   internal temperature reading in Fahrenheit. |  
internal-tempc | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.sensors.internal.temperature.internal-tempc | .1.3.6.1.4.1.20916.1.13.1.1.1.2 | INTEGER | read-only |   | ROOMALERT3S-MIB | The internal temperature reading   in Celsius. |  
digital | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.sensors.digital | .1.3.6.1.4.1.20916.1.13.1.2 |   |   |   | ROOMALERT3S-MIB |   |   |   |   |  
digital-sen1 | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.sensors.digital.digital-sen1 | .1.3.6.1.4.1.20916.1.13.1.2.1 |   |   |   | ROOMALERT3S-MIB |   |   |   |   |  
digital-sen1-1 | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.sensors.digital.digital-sen1.digital-sen1-1 | .1.3.6.1.4.1.20916.1.13.1.2.1.1 | INTEGER | read-only |   | ROOMALERT3S-MIB | The   sensor's current temperature in Celsius. |  
digital-sen1-2 | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.sensors.digital.digital-sen1.digital-sen1-2 | .1.3.6.1.4.1.20916.1.13.1.2.1.2 | INTEGER | read-only |   | ROOMALERT3S-MIB | The sensor's current temperature   in Fahrenheit. |  
digital-sen1-3 | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.sensors.digital.digital-sen1.digital-sen1-3 | .1.3.6.1.4.1.20916.1.13.1.2.1.3 | INTEGER | read-only |   | ROOMALERT3S-MIB | Varies   by sensor type:current % relative humidity, voltage reading (V), power state   (1=Power Detected, 0=No Power Detected), thermocouple temperature (C), or air   speed (m/s).
digital-sen1-4 | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.sensors.digital.digital-sen1.digital-sen1-4 | .1.3.6.1.4.1.20916.1.13.1.2.1.4 | INTEGER | read-only |   | ROOMALERT3S-MIB | Varies by sensor type:current   heat index (F), custom analog reading, thermocouple temperature (F), or air   speed (f/m).
digital-sen1-5 | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.sensors.digital.digital-sen1.digital-sen1-5 | .1.3.6.1.4.1.20916.1.13.1.2.1.5 | INTEGER | read-only |   | ROOMALERT3S-MIB | Varies   by sensor type:current heat index (C), thermocouple fault code (0=No Fault),   or air flow (CMH).
digital-sen1-6 | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.sensors.digital.digital-sen1.digital-sen1-6 | .1.3.6.1.4.1.20916.1.13.1.2.1.6 | INTEGER | read-only |   | ROOMALERT3S-MIB | Varies by sensor type:current   dew point (C) or air flow (CFM).
digital-sen1-7 | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.sensors.digital.digital-sen1.digital-sen1-7 | .1.3.6.1.4.1.20916.1.13.1.2.1.7 | INTEGER | read-only |   | ROOMALERT3S-MIB | Varies   by sensor type:current dew point (F). |  
switch | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.sensors.switch | .1.3.6.1.4.1.20916.1.13.1.3 |   |   |   | ROOMALERT3S-MIB |   |   |   |   |  
switch-sen1 | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.sensors.switch.switch-sen1 | .1.3.6.1.4.1.20916.1.13.1.3.1 | INTEGER | read-only |   | ROOMALERT3S-MIB | The   reading for switch sensor 1 (0 =OPEN, 1 =CLOSED).
traps | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.traps | .1.3.6.1.4.1.20916.1.13.2 |   |   |   | ROOMALERT3S-MIB |   |   |   |   |  
alarmmessage | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.traps.alarmmessage | .1.3.6.1.4.1.20916.1.13.2.1 | OCTET STRING | read-only |   | ROOMALERT3S-MIB | Last   Alarm Message |   |   |  
externalrelays | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.externalrelays | .1.3.6.1.4.1.20916.1.13.3 |   |   |   | ROOMALERT3S-MIB |   |   |   |   |  
externalrelay1 | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.externalrelays.externalrelay1 | .1.3.6.1.4.1.20916.1.13.3.1 |   |   |   | ROOMALERT3S-MIB |   |   |   |   |  
externalrelay1-element-one | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.externalrelays.externalrelay1.externalrelay1-element-one | .1.3.6.1.4.1.20916.1.13.3.1.1 | INTEGER | read-write |   | ROOMALERT3S-MIB | The status of the first element   on external relay 1. |  
externalrelay1-element-two | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.externalrelays.externalrelay1.externalrelay1-element-two | .1.3.6.1.4.1.20916.1.13.3.1.2 | INTEGER | read-write |   | ROOMALERT3S-MIB | The   status of the second element on external relay 1.
externalrelay1-element-three | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.externalrelays.externalrelay1.externalrelay1-element-three | .1.3.6.1.4.1.20916.1.13.3.1.3 | INTEGER | read-write |   | ROOMALERT3S-MIB | The status of the third element   on external relay 1. |  
externalrelay1-element-four | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.externalrelays.externalrelay1.externalrelay1-element-four | .1.3.6.1.4.1.20916.1.13.3.1.4 | INTEGER | read-write |   | ROOMALERT3S-MIB | The   status of the fourth element on external relay 1.
externalrelay1-element-five | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.externalrelays.externalrelay1.externalrelay1-element-five | .1.3.6.1.4.1.20916.1.13.3.1.5 | INTEGER | read-write |   | ROOMALERT3S-MIB | The status of the fifth element   on external relay 1. |  
externalrelay1-element-six | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.externalrelays.externalrelay1.externalrelay1-element-six | .1.3.6.1.4.1.20916.1.13.3.1.6 | INTEGER | read-write |   | ROOMALERT3S-MIB | The   status of the sixth element on external relay 1. |  
externalrelay1-element-seven | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.externalrelays.externalrelay1.externalrelay1-element-seven | .1.3.6.1.4.1.20916.1.13.3.1.7 | INTEGER | read-write |   | ROOMALERT3S-MIB | The status of the seventh   element on external relay 1.
externalrelay1-element-eight | .iso.org.dod.internet.private.enterprises.avtech.products.roomalert3S.externalrelays.externalrelay1.externalrelay1-element-eight | .1.3.6.1.4.1.20916.1.13.3.1.8 | INTEGER | read-write |   | ROOMALERT3S-MIB | The   status of the eighth element on external relay 1



</body>

</html>

**Comment by nr-dlaturner** [comment]
@viramamur The SNMP profile has been created via https://github.com/kentik/snmp-profiles/pull/498.   I am closing this issue.

**Comment by nr-dlaturner** [comment]
Resolved
