### ISSUE TITLE
[Missing SNMP Polling Profile] Watchguard Firewall M690/M390/M290

### ISSUE THREAD

**Issue by teohal** [kentik/snmp-profiles#500]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor:  Watchguard

Device Model:  Models: M690/M390/M290

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID):  
1.3.6.1.4.1.3097.1.5.96  for M690
1.3.6.1.4.1.3097.1.5.94 for M390
1.3.6.1.4.1.3097.1.5.93 for M290

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

General System Statistics (CPU, memory, throughput etc)
Traffic Flow Statistics between interfaces /VLANS

 
If there is a New Relic technical support case related to this request, please provide the case number:

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link:  https://gist.github.com/teohal/213cfb278f2e80a5c2576a29c350c438

---

**Comment by nr-dlaturner** [comment]
@teohal Please provide the SNMP walk output that includes the OID numbers, per the instructions.   We need to OID numbers to create a profile.  Thanks!

# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
