### ISSUE TITLE
[Missing SNMP Polling Profile] - Cradlepoint 

### ISSUE THREAD

**Issue by viramamur** [kentik/snmp-profiles#505]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: Cradlepoint

Device Model:  IBR650C-653

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): 
iso.3.6.1.2.1.1.1.0 = STRING: "Cradlepoint IBR650C-150M-D, Firmware Version 7.22.110.388605babc"
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.20992.2.32
iso.3.6.1.2.1.1.3.0 = Timeticks: (214805) 0:35:48.05
iso.3.6.1.2.1.1.4.0 = ""
iso.3.6.1.2.1.1.5.0 = STRING: "IBR650C-653.corp.copartcp.com"
iso.3.6.1.2.1.1.6.0 = STRING: "Unknown"
iso.3.6.1.2.1.1.7.0 = INTEGER: 78
iso.3.6.1.2.1.1.8.0 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.1.9.1.2.1 = OID: iso.3.6.1.6.3.11.3.1.1
iso.3.6.1.2.1.1.9.1.2.2 = OID: iso.3.6.1.6.3.15.2.1.1
iso.3.6.1.2.1.1.9.1.2.3 = OID: iso.3.6.1.6.3.10.3.1.1
iso.3.6.1.2.1.1.9.1.2.4 = OID: iso.3.6.1.6.3.1
iso.3.6.1.2.1.1.9.1.2.5 = OID: iso.3.6.1.2.1.49
iso.3.6.1.2.1.1.9.1.2.6 = OID: iso.3.6.1.2.1.4
iso.3.6.1.2.1.1.9.1.2.7 = OID: iso.3.6.1.2.1.50
iso.3.6.1.2.1.1.9.1.2.8 = OID: iso.3.6.1.6.3.16.2.2.1

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):
lte-modem signal-info
LTE Modem signal information:
    LTE:
         RSSI:       -71
         RSRQ:       -9
         RSRP:       -99
         SNR:        136

 
If there is a New Relic technical support case related to this request, please provide the case number:

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: 

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```
[nr_cradlepoint_snmpwalk.txt](https://github.com/kentik/snmp-profiles/files/10387250/nr_cradlepoint_snmpwalk.txt)
[nr_cradlepoint_snmpwalk.txt](https://github.com/kentik/snmp-profiles/files/10387251/nr_cradlepoint_snmpwalk.txt)
[nr_cradlepoint_snmpwalk.txt](https://github.com/kentik/snmp-profiles/files/10387253/nr_cradlepoint_snmpwalk.txt)
[nr_cradlepoint_snmpwalk.txt](https://github.com/kentik/snmp-profiles/files/10387255/nr_cradlepoint_snmpwalk.txt)

**Comment by viramamur** [comment]
NR Case #00084597

**Comment by merveille-tchouda** [comment]
@Mesverrum I see #531 was resolved should this issue be closed since they are tied together?

**Comment by viramamur** [comment]
we are not seeing the mib we requested
System Object Identifier (SysOID):
iso.3.6.1.2.1.1.1.0 = STRING: "Cradlepoint IBR650C-150M-D, Firmware Version 7.22.110.388605babc"
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.20992.2.32
iso.3.6.1.2.1.1.3.0 = Timeticks: (214805) 0:35:48.05
iso.3.6.1.2.1.1.4.0 = ""
iso.3.6.1.2.1.1.5.0 = STRING: "IBR650C-653.corp.copartcp.com"
iso.3.6.1.2.1.1.6.0 = STRING: "Unknown"
iso.3.6.1.2.1.1.7.0 = INTEGER: 78
iso.3.6.1.2.1.1.8.0 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.1.9.1.2.1 = OID: iso.3.6.1.6.3.11.3.1.1
iso.3.6.1.2.1.1.9.1.2.2 = OID: iso.3.6.1.6.3.15.2.1.1
iso.3.6.1.2.1.1.9.1.2.3 = OID: iso.3.6.1.6.3.10.3.1.1
iso.3.6.1.2.1.1.9.1.2.4 = OID: iso.3.6.1.6.3.1
iso.3.6.1.2.1.1.9.1.2.5 = OID: iso.3.6.1.2.1.49
iso.3.6.1.2.1.1.9.1.2.6 = OID: iso.3.6.1.2.1.4
iso.3.6.1.2.1.1.9.1.2.7 = OID: iso.3.6.1.2.1.50
iso.3.6.1.2.1.1.9.1.2.8 = OID: iso.3.6.1.6.3.16.2.2.1

**Comment by viramamur** [comment]
all we need is 
# trigger on wipipe modem status
$1 DISMAN-EVENT-MIB::mteTriggerValueID.\"test\".\'modemtrigger\' = .1.3.6.1.4.1.20992.1.2.2.1.5

**Comment by Mesverrum** [comment]
The OID 1.3.6.1.4.1.20992.1.2.2.1.5 is in the profile and would show in new relic as [mdmStatus](https://www.circitor.fr/Mibs/Html/W/WIPIPE-MIB.php#mdmStatus) with the enumerated values, but none of the walks you provided had any OID's from the the cradlepoint mib or the dismanEventMIB.  I'd suggest you start with troubleshooting why your walks do not include the expected OID's but that it not something we can fix for you.

**Comment by viramamur** [comment]
I dont see any mdmStatus using NRQL, could you please share me more details on it.

**Comment by viramamur** [comment]
ktranslate/snmp-yard-cradlepoint [Info] KTranslate Found profile for .1.3.6.1.4.1.20992.2.32: &{0xc000aa5100 [{WIPIPE-MIB {1.3.6.1.4.1.20992.1.2.2 mdmTable map[]    0 []  false  } [{1.3.6.1.4.1.20992.1.2.2.1.4 mdmSignalStrength map[]    0 []  false  } {1.3.6.1.4.1.20992.1.2.2.1.5 mdmStatus map[disconnected:5 disconnecting:6 empty:8 error:4 established:1 establishing:2 notconfigured:9 ready:3 suspended:7 userstopped:10]

**Comment by viramamur** [comment]
FROM Metric SELECT  * where metricName LIKE '%mdmStatus%'

**Comment by Mesverrum** [comment]
@viramamur I agree that the data is not showing up, but the point I'm making is that if you run snmpwalk against a device and the OID doesn't show up then we can't poll that OID from that device.  It doesn't exist, so we arent going to be able to collect it.  

None of your walks included anything from DISMAN-EVEN-MIB or from the Cradlepoint mibs, which I'd guess points to some kind of configuration error on the device that you will need to take up with the hardware vendor.  As soon as you get those OID's working and enabled then we will pick them up, but for the devices you are sending walks from the OID's aren't being exposed so nobody can collect them until you find the cause of that.

**Comment by viramamur** [comment]
![image](https://user-images.githubusercontent.com/101671545/218780796-a107029a-57d4-4e96-bea8-0ae6620d6c86.png)

**Comment by viramamur** [comment]
@Mesverrum  Please check below output. 
![image](https://user-images.githubusercontent.com/101671545/218781194-cb35f424-0587-4142-a718-66021d13da18.png)
