### ISSUE TITLE
Request for MIB registration of NetApp 7-mode (NetApp Release 8.2.3P6 7-Mode)

### ISSUE THREAD

**Issue by ootsuka-bnc** [kentik/snmp-profiles#506]
Hello. I'd like to do SNMP polling to old NetApp storage.

Device Vendor: NetApp

Device Model: FAS2554A

System Object Identifier (SysOID): enterprises.789.2.3

List of critical metrics that we expect in the profile

- disk space on the file systems

New Relic technical support case number: #00081436

Attached is the execution result of the snmpwalk command.

Thanks in advance.
[snmpwalk.txt](https://github.com/kentik/snmp-profiles/files/10389171/snmpwalk.txt)

**Comment by ootsuka-bnc** [comment]
Hello, Thank you for your response.
Attached are the results of running snmpwalk.



Best regards,
Makoto Ootsuka



送信元: "nr-dlaturner" ***@***.***>
宛先:   "kentik/snmp-profiles" ***@***.***>
Cc:     "ootsuka-bnc" ***@***.***>, "Mention" 
***@***.***>
日付:   2023/01/21 01:38
件名:   Re: [kentik/snmp-profiles] Request for MIB registration of NetApp 
7-mode (NetApp Release 8.2.3P6 7-Mode) (Issue #506)




@ootsuka-bnc Please provide the system OID and SNMP walk output that 
includes the OID numbers, per the instructions. We need the actual OID 
numbers to create a profile. Thanks!

v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> 
snmp_walk.out

v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x 
DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out

?
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: 
***@***.***>

**Comment by nr-dlaturner** [comment]
@ootsuka-bnc I don't see the new snmp walk file.  Can you please attach it or create and link a gist?

**Comment by ootsuka-bnc** [comment]
Hello, I uploaded a file. Can I see the contents?

Best regards,
Makoto Ootsuka
[snmp_walk_masked_out.txt](https://github.com/kentik/snmp-profiles/files/10507685/snmp_walk_masked_out.txt)

**Comment by ootsuka-bnc** [comment]
Hello, Thank you for your response.
I uploaded a file. I couldn't upload a file with the extension "out," so I 
changed the extension to "txt."

Best regards,
Makoto Ootsuka




送信元: "nr-dlaturner" ***@***.***>
宛先:   "kentik/snmp-profiles" ***@***.***>
Cc:     "ootsuka-bnc" ***@***.***>, "Mention" 
***@***.***>
日付:   2023/01/26 02:05
件名:   Re: [kentik/snmp-profiles] Request for MIB registration of NetApp 
7-mode (NetApp Release 8.2.3P6 7-Mode) (Issue #506)




@ootsuka-bnc I don't see the new snmp walk file.  Can you please attach it 
or create and link a gist?

?
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: 
***@***.***>

**Comment by nr-dlaturner** [comment]
1. Yes, I see the file now.  Thanks!

**Comment by ootsuka-bnc** [comment]
Thank you.
I have confirmed that I can do SNMP poll for NetApp FAS2554A.

Best regards,
Makoto Ootsuka



送信元: "Marc Netterfield" ***@***.***>
宛先:   "kentik/snmp-profiles" ***@***.***>
Cc:     "ootsuka-bnc" ***@***.***>, "Mention" 
***@***.***>
日付:   2023/01/31 10:53
件名:   Re: [kentik/snmp-profiles] Request for MIB registration of NetApp 
7-mode (NetApp Release 8.2.3P6 7-Mode) (Issue #506)




Closed #506 as completed via #530.

?
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: 
***@***.***>
