### ISSUE TITLE
Missing SNMP Polling Profile for cisco switch

### ISSUE THREAD

**Issue by sharathchandrareddys** [kentik/snmp-profiles#509]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: cisco

Device Model: cisco (CBS31X0 Software (CBS31X0-UNIVERSALK9-M), Version 12.2(58)SE1,)

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): 

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 Every metric
 
If there is a New Relic technical support case related to this request, please provide the case number:

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: 

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by Mesverrum** [comment]
@sharathchandrareddys We need you to provide the snmp walk for one of these devices in order to build a profile.

**Comment by sharathchandrareddys** [comment]
[cisco switch walkout.txt](https://github.com/kentik/snmp-profiles/files/10481036/cisco.switch.walkout.txt)

**Comment by northyg** [comment]
@Mesverrum Walkout has been uploaded. Do we need anything else from @sharathchandrareddys to add this to backlog?

**Comment by sharathchandrareddys** [comment]
Hey @Mesverrum 


we are not able to get the services for the devices , could you please look into this,let me know if you require anything

**Comment by Mesverrum** [comment]
We've added the device to the profile.  You should remove your old docker instance, pull the latest version and start a fresh container and have it discover the device again.  It will map any devices with the 1.3.6.1.4.1.9.1.948 sys oid to the cisco profile.

**Comment by sharathchandrareddys** [comment]
hey @Mesverrum 

i have tried that too a couple of times

**Comment by sharathchandrareddys** [comment]
hello @Mesverrum 

any update on this ?

**Comment by sharathchandrareddys** [comment]
hello @Mesverrum 

any update on this?
