### ISSUE TITLE
Missing SNMP Polling Profile for Baicells pBS2120

### ISSUE THREAD

**Issue by sharathchandrareddys** [kentik/snmp-profiles#510]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: Baicells 
https://na.baicells.com/

Device Model: pBS2120

System Object Identifier (SysOID): 

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 Possible interface metrics and host metrics

**Comment by sharathchandrareddys** [comment]
SNMP MIB: [https://na.baicells.com/download/RTS%203.6%20BAICELLS-MIB.mib 72](https://na.baicells.com/download/RTS%203.6%20BAICELLS-MIB.mib)
SNMP Alarm MIB: https://na.baicells.com/download/RTS%203.6%20ALARMTRAPS-MIB.mib

**Comment by Mesverrum** [comment]
@sharathchandrareddys We do not build profiles from mib files, we need the snmp walk as directed in the issue template.

**Comment by sharathchandrareddys** [comment]
> Device Vendor: Baicells https://na.baicells.com/
> 
> Device Model: pBS2120
> 
> System Object Identifier (SysOID):
> 
> List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):
> 
> Possible interface metrics and host metrics

> snmp walkout
.1.3.6.1.2.1.1.1.0 = STRING: "Linux CELL 3.0.51-rt75 #1 SMP PREEMPT RT Fri Oct 15 19:41:55 HKT 2021 armv7l"
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.8072.3.2.10
.1.3.6.1.2.1.1.3.0 = Timeticks: (2483751377) 287 days, 11:18:33.77
.1.3.6.1.2.1.1.4.0 = STRING: "bofh@example.com"
.1.3.6.1.2.1.1.5.0 = STRING: "HeartOfGold"
.1.3.6.1.2.1.1.6.0 = STRING: "office"
.1.3.6.1.2.1.1.8.0 = Timeticks: (645) 0:00:06.45
.1.3.6.1.2.1.1.9.1.2.1 = OID: .1.3.6.1.2.1.4
.1.3.6.1.2.1.1.9.1.2.2 = OID: .1.3.6.1.6.3.1
.1.3.6.1.2.1.1.9.1.2.3 = OID: .1.3.6.1.2.1.49
.1.3.6.1.2.1.1.9.1.2.4 = OID: .1.3.6.1.2.1.50
.1.3.6.1.2.1.1.9.1.2.5 = OID: .1.3.6.1.6.3.16.2.2.1
.1.3.6.1.2.1.1.9.1.2.6 = OID: .1.3.6.1.6.3.10.3.1.1
.1.3.6.1.2.1.1.9.1.2.7 = OID: .1.3.6.1.6.3.11.3.1.1
.1.3.6.1.2.1.1.9.1.2.8 = OID: .1.3.6.1.6.3.15.2.1.1
.1.3.6.1.2.1.1.9.1.3.1 = STRING: "The MIB module for managing IP and ICMP implementations"
.1.3.6.1.2.1.1.9.1.3.2 = STRING: "The MIB module for SNMPv2 entities"
.1.3.6.1.2.1.1.9.1.3.3 = STRING: "The MIB module for managing TCP implementations"
.1.3.6.1.2.1.1.9.1.3.4 = STRING: "The MIB module for managing UDP implementations"
.1.3.6.1.2.1.1.9.1.3.5 = STRING: "View-based Access Control Model for SNMP."
.1.3.6.1.2.1.1.9.1.3.6 = STRING: "The SNMP Management Architecture MIB."
.1.3.6.1.2.1.1.9.1.3.7 = STRING: "The MIB for Message Processing and Dispatching."
.1.3.6.1.2.1.1.9.1.3.8 = STRING: "The management information definitions for the SNMP User-based Security Model."
.1.3.6.1.2.1.1.9.1.4.1 = Timeticks: (645) 0:00:06.45
.1.3.6.1.2.1.1.9.1.4.2 = Timeticks: (645) 0:00:06.45
.1.3.6.1.2.1.1.9.1.4.3 = Timeticks: (645) 0:00:06.45
.1.3.6.1.2.1.1.9.1.4.4 = Timeticks: (645) 0:00:06.45
.1.3.6.1.2.1.1.9.1.4.5 = Timeticks: (645) 0:00:06.45
.1.3.6.1.2.1.1.9.1.4.6 = Timeticks: (645) 0:00:06.45
.1.3.6.1.2.1.1.9.1.4.7 = Timeticks: (645) 0:00:06.45
.1.3.6.1.2.1.1.9.1.4.8 = Timeticks: (645) 0:00:06.45
.1.3.6.1.2.1.2.1.0 = INTEGER: 5
.1.3.6.1.2.1.2.2.1.1.1 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.1.2 = INTEGER: 2
.1.3.6.1.2.1.2.2.1.1.3 = INTEGER: 3
.1.3.6.1.2.1.2.2.1.1.4 = INTEGER: 4
.1.3.6.1.2.1.2.2.1.1.5 = INTEGER: 5
.1.3.6.1.2.1.2.2.1.2.1 = STRING: "lo"
.1.3.6.1.2.1.2.2.1.2.2 = STRING: "eth1"
.1.3.6.1.2.1.2.2.1.2.3 = STRING: "eth2"
.1.3.6.1.2.1.2.2.1.2.4 = STRING: "tunl0"
.1.3.6.1.2.1.2.2.1.2.5 = STRING: "ip6tnl0"
.1.3.6.1.2.1.2.2.1.3.1 = INTEGER: 24
.1.3.6.1.2.1.2.2.1.3.2 = INTEGER: 6
.1.3.6.1.2.1.2.2.1.3.3 = INTEGER: 6
.1.3.6.1.2.1.2.2.1.3.4 = INTEGER: 131
.1.3.6.1.2.1.2.2.1.3.5 = INTEGER: 131
.1.3.6.1.2.1.2.2.1.4.1 = INTEGER: 1500
.1.3.6.1.2.1.2.2.1.4.2 = INTEGER: 1500
.1.3.6.1.2.1.2.2.1.4.3 = INTEGER: 1500
.1.3.6.1.2.1.2.2.1.4.4 = INTEGER: 1480
.1.3.6.1.2.1.2.2.1.4.5 = INTEGER: 1452
.1.3.6.1.2.1.2.2.1.5.1 = Gauge32: 10000000
.1.3.6.1.2.1.2.2.1.5.2 = Gauge32: 1000000000
.1.3.6.1.2.1.2.2.1.5.3 = Gauge32: 1000000000
"snmp_baicels_walk.out" 825L, 38302C

**Comment by merveille-tchouda** [comment]
@Mesverrum hey looks like @sharathchandrareddys posted the walk is there anything needed from him at this time?

**Comment by Mesverrum** [comment]
@sharathchandrareddys The OID's in your walk show your device does not expose anything that is not already captured with the base profile we collect from all net-snmp based appliances.  There's nothing to build for a profile.
