### ISSUE TITLE
YML File for a device room alert version 3E

### ISSUE THREAD

**Issue by EddGH1337** [kentik/snmp-profiles#513]
Hello, we request your help in order to get the roomalert.yml for a device version 3E.
This because we currently have the kentik roomalert.yml for a device version 3S and we need the file for version roomalerts3e.

We are attaching the file ROOMALERT3E.MIB for further details.
As additional information we perform tests with the current roomalerts.yml for version 3S  (avtech) and it didn't work.

We apologize for the error with the description at the Issue #511
[RA3E-MIB.zip](https://github.com/kentik/snmp-profiles/files/10440694/RA3E-MIB.zip)

**Comment by Mesverrum** [comment]
Based on the instructions when you open an issue in this repo, we don't use MIB files to create profiles, we would need an SNMP walk from the device that you are trying to monitor.  Please provide the information requested in the template


[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: 

Device Model: 

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): 

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - 
 -
 -
 
If there is a New Relic technical support case related to this request, please provide the case number:

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: 

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by EddGH1337** [comment]
Hi Marc, we are sending you the requested information in the attached file "RoomAlert3E_information.txt"

Thanks in advance for your help.
[RoomAlert3E_information.zip](https://github.com/kentik/snmp-profiles/files/10452022/RoomAlert3E_information.zip)

**Comment by EddGH1337** [comment]
Hi Marc,
It's been a couple of days without updates. We would like to knows if there have been any advance with the roomalert.yml for a device version 3E requested?

**Comment by EddGH1337** [comment]
Hi Marc,

It's been a couple of days without updates or any notifications from you. 
We would like to knows if there have been any advance with the roomalert.yml for a device version 3E requested?

We do really need your help.

Have a nice day.

**Comment by Mesverrum** [comment]
@EddGH1337 This repo is best effort from our side, so you'll have to be patient.   It is in the back log and it will be completed as we get to them, you are also free to create a profile and submit it as a PR by using the existing profiles and the[ template document](https://github.com/kentik/snmp-profiles/blob/main/profiles/kentik_snmp/_template.yml) for reference.
