### ISSUE TITLE
Missing SNMP Polling Profile - TP-Link T1600G-52PS V4

### ISSUE THREAD

**Issue by RFXTECH** [kentik/snmp-profiles#518]
Device Vendor:  TP-Link

Device Model: T1600G-52PS V4
Mibs can be found here: https://www.tp-link.com/us/support/download/t1600g-52ps/

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID):  sysObjectID.0 = OID: SNMPv2-SMI::enterprises.11863.5.38

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):
Normal Switch Metrics

 
If there is a New Relic technical support case related to this request, please provide the case number:  New Relic support case created: Case #00086394

Gist Link:  https://gist.github.com/RFXTECH/135ac032133f0f412752b3b22f8b2b29

**Comment by nr-dlaturner** [comment]
@RFXTECH  Please provide the numerical system OID and complete SNMP walk output that includes the OID numbers, per the instructions. We need the actual OID numbers to create a profile. Thanks!

v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out

**Comment by RFXTECH** [comment]
the full snmpwalk is on the gist link above.  Also, https://github.com/kentik/snmp-profiles/issues/458 was the same brand tp-link but a different model.   I pulled below the tplink website, is 11863.5 the OID or this switch?

TPLINK-MIB DEFINITIONS ::= BEGIN


    IMPORTS
        enterprises 
					FROM RFC1155-SMI
		OBJECT-IDENTITY
					FROM SNMPv2-SMI;

	tplink 			OBJECT IDENTIFIER ::= { enterprises 11863 }

	switch			OBJECT IDENTIFIER ::= { tplink 1 }
	router			OBJECT IDENTIFIER ::= { tplink 2 }
	wireless		OBJECT IDENTIFIER ::= { tplink 3 }
	adsl			OBJECT IDENTIFIER ::= { tplink 4 }
	
	
	tplinkProducts	OBJECT-IDENTITY
		STATUS  	current
		DESCRIPTION
			"tplinkProducts is the root OBJECT IDENTIFIER from
			which sysObjectID values are assigned.  Actual
			values are defined in TPLINK-PRODUCTS-MIB."
		::= { tplink 5 }
		
	tplinkMgmt	OBJECT-IDENTITY		
		STATUS	current
		DESCRIPTION
			"tplinkMgmt is the main subtree for new mib development."

		::= { tplink 6 }

END

**Comment by RFXTECH** [comment]
ok thank you, I was missing the "-ObentU"   
https://gist.github.com/RFXTECH/135ac032133f0f412752b3b22f8b2b29
Ok I updated the gist link above and here is the OID
.1.3.6.1.2.1.1.1.0 = STRING: JetStream 48-Port Gigabit Smart PoE+ Switch with 4 SFP Slots
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.11863.5.38

**Comment by Mesverrum** [comment]
@RFXTECH The walk you provided seems like it may not have been the complete walk to be sure, but I updated the sysoid's section of the existing tplink switch profile to also include this branch as I believe they use the same CPU/Memory counter for both product lines.  Drop a new issue if they don't come in after you get the updated profile.

**Comment by RFXTECH** [comment]
Thank you!  I updated the container and the device is now showing under "kentik-default .1.3.6.1.4.1.11863.5.38  February 08, 2023 13:15:00"  It still doesn't know it's a switch.

**Comment by Mesverrum** [comment]
That's on me, put a 6 where i needed a 5
