### ISSUE TITLE
[Missing SNMP Polling Profile] Thales Luna Network HSM

### ISSUE THREAD

**Issue by astenka** [kentik/snmp-profiles#519]
Device Vendor:  Thales

Device Model: Luna Network HSM (6 and 7) Luna SP HSM

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): .1.3.6.1.4.1.12383.3.1.1

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - cpu user, system, idle, interrupts, context_switches (UCD-SNMP-MIB)
 - memory avail real, memory cached, memory total real (UCD-SNMP-MIB)
 - interface traffic (IF-MIB)
 - tcp connections: established, established_resets, out_resets (TCP-MIB)
 - hsm operation requests, hsm_operation_errors, ntls_connected_clients (CHRYSALIS-UTSP-MIB::hsmOperationRequests.0, CHRYSALIS-UTSP-MIB::hsmOperationErrors.0, CHRYSALIS-UTSP-MIB::ntlsConnectedClients.0)
 
If there is a New Relic technical support case related to this request, please provide the case number: #00087225

Gist link: https://gist.github.com/astenka/9591795ca8ce1107d0464e0a47efa2b5

---

**Comment by Mesverrum** [comment]
The profile for this is built so that will let ktranslate collect data about these devices, but since this is a new device type we don't any pre-built GUI on the New Relic side to use this data so you won't see an entity in the explorer until we get that in. Once we get a chance to build an [entity definition](https://github.com/newrelic/entity-definitions) you won't have to do anything on your end, it will just pop into existence on the explorer view.

**Comment by astenka** [comment]
Thank you - should i create an issue to build this new entity definition ?

**Comment by astenka** [comment]
I am not sure if this is correct:

- MIB: PowerNet-MIB_PDU

Why PDU MIB is used in the profile ?

**Comment by Mesverrum** [comment]
No need to create an issue,  and like I said there's nothing you need to do.   For now if you've loaded the profile then you can find the device  stats coming in as custom data in NRQL. You could use something like 

select * from Metric where instrumentation.name = 'luna-hsm'


And you are right about the mib name being off, that's copy pasta on my end and I'll update it.   That field in the profile is informational only so it shouldn't impact collecting the data.
