### ISSUE TITLE
[Missing SNMP Polling Profile] Barracuda CloudGen Firewall F380b

### ISSUE THREAD

**Issue by neonunit** [kentik/snmp-profiles#520]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: Barracuda Networks

Device Model: CloudGen Firewall F380b

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): .1.3.6.1.4.1.10704.1.10

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - Hardware Sensors (CPU / MEM util, disk space, temperatures)
 - Licensing (ok/expired/grace period)
 - Concurrent VPN Users Online
 - interface throughput
 
If there is a New Relic technical support case related to this request, please provide the case number:

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: https://gist.github.com/neonunit/2ed765af7c771886a3b024ec82b6a249

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by neonunit** [comment]
MIB descriptions: https://campus.barracuda.com/product/cloudgenfirewall/doc/95259178/phion-mib-field-descriptions/

**Comment by neonunit** [comment]
Thanks! Looks like the device is now recognized. However, some data fetched don't seem to be correct, for example memory utilization:

From New Relic:
![obraz](https://user-images.githubusercontent.com/16742059/217772881-c80fcb42-cdc3-4da9-96d9-483a7e8a9898.png)

From Firewall Admin management app:
![obraz](https://user-images.githubusercontent.com/16742059/217772981-384f8000-2c38-4b77-bf59-51f5d10b380f.png)

**Comment by Mesverrum** [comment]
There's some UI work to do on the NR side since this is a new device family.  If you email me at mnetterfield@newrelic.com I can take a look at the data in your account and update the widgets to display the right OID's for this device.
