### ISSUE TITLE
[LENOVO-MGR-MIB Missing SNMP Polling Profile]

### ISSUE THREAD

**Issue by tapanswain1** [kentik/snmp-profiles#521]
[NOTE]: # ( ^^ Please add the lenovoManager Vendor and Model in the title above. ^^ )

Device Vendor:  lenovoManager

Device Model: xclarity

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): iso.3.6.1.4.1.4976

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - Lenovo management event trap MIB
 -
 -
 
If there is a New Relic technical support case related to this request, please provide the case number:

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: 
iso.3.6.1.2.1.1.1.0 = STRING: "SNMP4J-Agent - Linux - amd64 - 5.4.167-yocto-standard"
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.4976
iso.3.6.1.2.1.1.3.0 = Timeticks: (500811930) 57 days, 23:08:39.30
iso.3.6.1.2.1.1.4.0 = ""
iso.3.6.1.2.1.1.5.0 = ""
iso.3.6.1.2.1.1.6.0 = ""
iso.3.6.1.2.1.1.7.0 = INTEGER: 10
iso.3.6.1.2.1.1.8.0 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.11.1.0 = Counter32: 101177
iso.3.6.1.2.1.11.3.0 = Counter32: 0
iso.3.6.1.2.1.11.4.0 = Counter32: 834
iso.3.6.1.2.1.11.5.0 = Counter32: 0
iso.3.6.1.2.1.11.6.0 = Counter32: 0
iso.3.6.1.2.1.11.30.0 = INTEGER: 1
iso.3.6.1.2.1.11.31.0 = Counter32: 0
iso.3.6.1.2.1.11.32.0 = Counter32: 0

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by tapanswain1** [comment]
we want to integarte xclarity with Newrelic , so when xclarity send out alert  we can process this .

**Comment by tapanswain1** [comment]
lenovoMgrAlert.mib file

https://sysmgt.lenovofiles.com/help/index.jsp?topic=%2Fcom.lenovo.lxca.doc%2Fevents_mib.html

**Comment by tapanswain1** [comment]
i tried to run snmp v1 version , but  there is no response we are getting from the device .  looks  like xclarity device does not repond to snmpv1 .  

it only support snmp v1  and snmpv3 .  

<img width="354" alt="image" src="https://user-images.githubusercontent.com/1785320/216208481-9746cca1-bec0-465f-b386-325928151434.png">

**Comment by Mesverrum** [comment]
@tapanswain1 I know we discussed this a bit on the call but just for the sake of the repo housekeeping.  You'll need to have ktranslate set up to receive the inbound traps from your event tool.  No profile is needed to ingest traps, everything that hits the container on port 162 is ingested by default.  Once you have events coming in if you want you can build trap profiles to map the varbind OID numbers to more human friendly names to display as the column headers, but even without a profile the traps will be ingested as they are.
