### ISSUE TITLE
Missing SNMP Polling Profile for Tripp Lite - Eaton

### ISSUE THREAD

**Issue by sharathchandrareddys** [kentik/snmp-profiles#536]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: Triiplite

Device Model: UPS
[SNMPwalk_triiplite Ups.txt](https://github.com/kentik/snmp-profiles/files/10558813/SNMPwalk_triiplite.Ups.txt)

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): 

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

•	PDU outlets plugin
•	PDU - Ping, CPU, Memory, Uptime
•	PDU - Model and version -snmp info
•	Input output voltage  
•	Load 
•	Temperature
•	Input Phase 
•	self-test
•	system events
•	Phase output

 
If there is a New Relic technical support case related to this request, please provide the case number:

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: 

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by Mesverrum** [comment]
Resolved by #550.  Keep in mind that since this is a new device and vendor the OOTB dashboard for this probably won't catch most of the device specific OIDs.  We'll build that on the NR side and within 5-10 business days you should expect a new entity view to drop in for these.

**Comment by sharathchandrareddys** [comment]
hi @Mesverrum ,

we have created the docker once again but still we are seeing them under the kentike defaults with no metrics (device profile missing),could you please have a look into this ,if any please revert us back.
Requesting you to take it as apriority.

![image](https://user-images.githubusercontent.com/57246805/219264053-f07a8b77-aacc-4a8f-8886-8ef04f9c8c20.png)

**Comment by sharathchandrareddys** [comment]
@Mesverrum  

any update on this?

**Comment by sharathchandrareddys** [comment]
hello @Mesverrum ,

any update on this?
