### ISSUE TITLE
[Missing SNMP Polling Profile] Netgear WAX620 WiFi 6 AX3600 2.5Gbit Access Point

### ISSUE THREAD

**Issue by mileperhour** [kentik/snmp-profiles#541]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: NETGEAR

Device Model: WAX620

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): .1.3.6.1.4.1.4526.100.7.15

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - SSID status, vlan, links, stats, errors, etc...
 - Client SSID Associations, Failed, etc..
 - Interface status, statistics, error, discards, etc...
 - Traffic counters
 

 
If there is a New Relic technical support case related to this request, please provide the case number: No

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: https://gist.github.com/mileperhour/5daaabab44b9a708f82821b0f6a5bdac

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by Mesverrum** [comment]
The walk you provided did not have any vendor specific OID's, and I could not find any published MIBs for this product family.  This profile will categorize the device as an AP and it will collect the interface bandwidth metrics, but this device does not expose anything about the SSID's or clients via SNMP.

From what I saw this is a cloud managed AP, similar to a Meraki, and just like those devices you can't get much info from the device directly. In the case of Meraki we have to connect to their central management UI to get anything useful, I would expect that Netgear does something similar.  If Netgear has an API you can most likely integrate it with New Relic by writing a custom flex script or by finding a prometheus exporter for that API and using remote-write to send the stats directly to New Relic.
