### ISSUE TITLE
HP Blade Servers 

### ISSUE THREAD

**Issue by viramamur** [kentik/snmp-profiles#557]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor:  HP 

Device Model:  ProLiant BL460c Gen9

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): 

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 -  Blade Metrics
 -  Hardware Status
 -  Default alerting
 
If there is a New Relic technical support case related to this request, please provide the case number:

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: 

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by viramamur** [comment]
[snmpwalk_BL460C.txt](https://github.com/kentik/snmp-profiles/files/10744814/snmpwalk_BL460C.txt)

**Comment by viramamur** [comment]
Support CASE# Case #00093533 |

**Comment by Mesverrum** [comment]
@viramamur 
This profile is being merged in now.  
We don't have an entity defined in the NR ui for these kinds of appliances yet, so you won't see them immediately on the explorer menu, but after you get the new profile and add the devices in if you check in NRQL the available data will show up. I'll get the entity definition in place for this so when that happens on our back end the device will pop into your UI, that step is likely to take 5-10 business days from now.

**Comment by viramamur** [comment]
Thie profile is name added yet hpe-bladesystem-enclosure.yml.  I noticed the merging is blocked.

**Comment by viramamur** [comment]
The profile Is still not added to the docker image.

Regarding HP Blade server the profile is not added.
hpe-bladesystem-enclosure.yml
