### ISSUE TITLE
Missing SNMP Polling Profile for APC PDU

### ISSUE THREAD

**Issue by sharathchandrareddys** [kentik/snmp-profiles#562]
Device Vendor: APC

Device Model: 
[snmpwalk_APCPDU_HQ.txt](https://github.com/kentik/snmp-profiles/files/10776332/snmpwalk_APCPDU_HQ.txt)

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): 

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

-  PDU outlets plugin
• PDU - Ping, CPU, Memory, Uptime
• PDU - Model and version -snmp info
• Input output voltage
• Load
• Temperature
• Input Phase
• self-test
• system events
• Phase output

 
If there is a New Relic technical support case related to this request, please provide the case number:

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: 

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by sharathchandrareddys** [comment]
Hello Team,

Any update on this ?

**Comment by Mesverrum** [comment]
This sysoid is already captured by the profile https://github.com/kentik/snmp-profiles/blob/main/profiles/kentik_snmp/apc/apc_pdu.yml and it looks that this profile already has the bulk of what you are asking for.  CPU and memory don't get reported for appliances like a PDU but the input and output voltage info and such and model info are already there. IIRC the system events for APC asre sent out as traps, which is not part of the polling profiles. If there are some specific OIDs that you know of that you want to add feel free to reopen this issue and specify the oids you want to include in the existing profile.

**Comment by sharathchandrareddys** [comment]
hey @Mesverrum ,

Thanks for the reply,

I need the below to be displayed on the dash board, but i am seeing only pdu details ,uptime ,outlet status mainly i need the below to be displayed on the dash boards

PDU outlets plugin
• PDU - Ping, CPU, Memory, Uptime
• PDU - Model and version -snmp info
• Input output voltage
• Load
• Temperature
• Input Phase
• self-test
• system events
• Phase output
