### ISSUE TITLE
AVTECH RoomAlert 32S

### ISSUE THREAD

**Issue by AlkamiNathan** [kentik/snmp-profiles#566]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: AVTECH (https://avtech.com/)

Device Model: RoomAlert 32S (https://avtech.com/Products/Environment_Monitors/Room_Alert_32S/Responder.htm)

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): .1.3.6.1.4.1.20916

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - Internal sensor values (.1.3.6.1.4.1.20916.1.11.1.*)
 - Digital sensor values (.1.3.6.1.4.1.20916.1.11.2.*)
 - Switch sensor values (.1.3.6.1.4.1.20916.1.11.1.3.*)
 
If there is a New Relic technical support case related to this request, please provide the case number:

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: https://gist.github.com/AlkamiNathan/94d64e31b90d7fd94bfc121900c7f0a7

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by Mesverrum** [comment]
Hi @AlkamiNathan, are you able to get a MIB file from the vendor portal or the device itself [as documented here ](https://avtech.com/articles/6724/find-room-alert-mib-files/)?

From what I've picked up doing these profiles AVTech seems to publish a separate mib tailored to each model and I can't find anything online that documents what the 1.3.6.1.4.1.20916.1.11 MIB is supposed to contain.  I could make some guesses based on what I'm finding for other models but I'd hate to guess if you can provide the actual file.

**Comment by AlkamiNathan** [comment]
I've added the MIB file to the gist: https://gist.github.com/AlkamiNathan/94d64e31b90d7fd94bfc121900c7f0a7#file-avtech_roomalert_32s-mib

**Comment by AlkamiNathan** [comment]
Any update on this profile request?
