### ISSUE TITLE
[Missing SNMP Profile] Ubiquiti Unifi

### ISSUE THREAD

**Issue by hucknz** [kentik/snmp-profiles#57]
Device Vendor: Ubiquiti

Device Model: Unifi

System Object Identifier (SysOID): 

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - Support for out of box Unifi OS MIB's

Vendor provided MIB file is available here: http://dl.ubnt-ut.com/snmp/UBNT-UniFi-MIB

**Comment by thezackm** [comment]
@hucknz  - Please provide a [public gist](https://gist.github.com/) with a sanitized SNMP walk of the device (sensitive information removed) so we can start building this profile. Thank you.

Example SNMP walk commands:

```
# v2c example
snmpwalk -v 2c -On -c $COMMUNITY_STRING $IP_ADDRESS . >> ubiquiti_unifi.out

# v3 example
snmpwalk -v3 -On -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS $IP_ADDRESS . >> ubiquiti_unifi.out
```

**Comment by hucknz** [comment]
@thezackm here are the gists. I've run an snmpwalk on all the device types I have access to. 

https://gist.github.com/hucknz/bfa1c95727b98fbf950889e13ce1ab4b
https://gist.github.com/hucknz/3486fa34d375c3ea2b8e1c128751dfd0
https://gist.github.com/hucknz/6d6128f2d4e90705849f2707547bba01
https://gist.github.com/hucknz/bd0ea3ef6bcd9f7f02ff8a24a7853673
