### ISSUE TITLE
[Missing SNMP Polling Profile] Aruba 6200F

### ISSUE THREAD

**Issue by copypastepro** [kentik/snmp-profiles#577]
Device Vendor: Aruba

Device Model: 6200F

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): .1.3.6.1.4.1.47196.4.1.1.1.304

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - up and down for interfaces
 - health of network switch (cpu, memory, temp, fan, psu etc)
 - firmware version, usage/utilizations, 
 
If there is a New Relic technical support case related to this request, please provide the case number:

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: Case #00095745
---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
[Aruba-switch-snmpwalk-clean.txt](https://github.com/kentik/snmp-profiles/files/10883569/Aruba-switch-snmpwalk-clean.txt)

snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by copypastepro** [comment]
Could I get an update on this?

Thanks!

**Comment by copypastepro** [comment]
Could I get an update on this?

Thanks

**Comment by nr-dlaturner** [comment]
@copypastepro Can you please provide a sanitized SNMP walk from your device, per the instructions? We can not create a profile without this information. Thanks!

**Comment by nr-dlaturner** [comment]
Closed by mistake

**Comment by copypastepro** [comment]
I thought the file was sanitized, but I’ll double-check.
Thanks for the update.

Thanks,


[Shape  Description automatically generated with medium confidence]
Jose Rosales
Network Administrator
C: 832-455-7773
axiomspace.com<http://www.axiomspace.com/>
[A picture containing text, clipart  Description automatically generated]

**Comment by copypastepro** [comment]
[Aruba-switch-snmpwalk-clean.txt](https://github.com/kentik/snmp-profiles/files/10958857/Aruba-switch-snmpwalk-clean.txt)

Please try now. I've replaced everything inside of "XXX" with "null". 
Please let me know if there's a better way of cleaning the file.

**Comment by copypastepro** [comment]
Would like to add support to monitor switch temperature for cx series switches.
Please reference case#00101914
