### ISSUE TITLE
Missing SNMP Polling Profile rairitan ups

### ISSUE THREAD

**Issue by sharathchandrareddys** [kentik/snmp-profiles#601]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: Rairitan

Device Model: PX2 030520

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): 

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - • PDU outlets plugin
• PDU - Ping, CPU, Memory, Uptime
• PDU - Model and version -snmp info
• Input output voltage
• Load
• Temperature
• Input Phase
• self-test
• system events
• Phase output
[snmpwalk_rairitanups.txt](https://github.com/kentik/snmp-profiles/files/11059078/snmpwalk_rairitanups.txt)

 -
 -
 
If there is a New Relic technical support case related to this request, please provide the case number:

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: 

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by sharathchandrareddys** [comment]
hi @Mesverrum ,

could you please take care of this.

**Comment by sharathchandrareddys** [comment]
Hello Team,

This not solved we are seeing the devices still in the Kentik Defaults, requesting you to build the profile for these PDU's

**Comment by Mesverrum** [comment]
I apologize for the delayed response, there has been a change with the way SNMP profiles are handled.  In the interest of not being a bottleneck, SNMP profiles are now to be handled as a self-service item for users of ktranslate.  Your organization should fork this repo or copy the contents and make any desired changes directly there, you can see an example of how to pass a modified fork of the profile definitions in [this documentation](https://docs.newrelic.com/docs/network-performance-monitoring/advanced/snmp-profiles/).  You can find documentation of the syntax and capabilities of the profile definitions in this [template](https://github.com/kentik/snmp-profiles/blob/main/profiles/kentik_snmp/_template.yml).
There will be no need for approvals or review except those you implement within your own fork for yourselves.
