### ISSUE TITLE
[Missing SNMP Profile] CISCO 10-Port Gigabit Managed Switch

### ISSUE THREAD

**Issue by Ratchanad** [kentik/snmp-profiles#61]
Device Vendor: Cisco

Device Model: SG 300-10 10-Port Gigabit Managed Switch

System Object Identifier (SysOID): .1.3.6.1.4.1.9.6.1.83.10.1

Serial Number: PSJ16160AYL

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

all metrics related to mib id.txt

[cisco mib id.txt](https://github.com/kentik/snmp-profiles/files/7509643/cisco.mib.id.txt)

**Comment by thezackm** [comment]
@Ratchanad - - please provide an snmpwalk output from your device so we can add this to our queue for building new profiles. thanks!

>Please provide a public gist with a sanitized (sensitive information removed) SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.

Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -On -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS $IP_ADDRESS . >> snmp_walk.out
```

**Comment by Ratchanad** [comment]
> @Ratchanad - - please provide an snmpwalk output from your device so we can add this to our queue for building new profiles. thanks!
> 
> > Please provide a public gist with a sanitized (sensitive information removed) SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.
> 
> Example SNMP walk commands:
> 
> ```
> # v2c example
> snmpwalk -v 2c -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out
> 
> # v3 example
> snmpwalk -v3 -On -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS $IP_ADDRESS . >> snmp_walk.out
> ```


# v2c example
snmpwalk -v 2c -On -c public 172.16.0.14 >> snmp_walk.out
[snmp_walk.zip](https://github.com/kentik/snmp-profiles/files/7561482/snmp_walk.zip)

**Comment by Mesverrum** [comment]
Thanks, this is in queue to get a profile built, after the issue closes you will want to pull the latest image and rediscover these devices.

**Comment by thezackm** [comment]
PR has been submitted for review; note this device has no CPU or Memory metrics based on the results of the SNMP walk provided

**Comment by Ratchanad** [comment]
PR can check What metrics can the device detect?

**Comment by thezackm** [comment]
@Ratchanad - this device has been added under the general Cisco switch profile [here](https://github.com/kentik/snmp-profiles/blob/8f2a011fdb406c38a979b1d3e84173cbe18b7af0/profiles/kentik_snmp/cisco/cisco-catalyst.yml#L374)

Active collection is enabled on all metrics on that profile; along with the profiles shown in the `extends` section at teh top of the YAML; the `ktranslate` container will poll against all of the listed OIDs and return data for every metric that the device supports, as evidenced by the provided SNMP walk.

---
Closing with #82
