### ISSUE TITLE
Missing SNMP Polling Profile for HP ILO  GEN 10

### ISSUE THREAD

**Issue by cnuamrutha** [kentik/snmp-profiles#637]
Device Vendor:  HP 

Device Model: Synergy 480 Gen10

System Object Identifier (SysOID): 

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

Interface link status
Uptime
Controller Status
CPU%
Memory%
Fibre link status
Hardware Status
Drive Details
Fan Details
Power Supply Details
 -
 -
 
If there is a New Relic technical support case related to this request, please provide the case number:

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: 

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

[snmpwalk_hp_ilo_gen10.txt](https://github.com/kentik/snmp-profiles/files/11264123/snmpwalk_hp_ilo_gen10.txt)

**Comment by Mesverrum** [comment]
@cnuamrutha This request is not quite adding up for me, there is already a [profile](https://github.com/kentik/snmp-profiles/blob/main/profiles/kentik_snmp/hp/hp-ilo.yml) that would capture the sysOID you provided in your walk, so this device should already be working as-is, assuming your are using a version of ktranslate newer than Nov 8th, 2022.  Based your request I just added the if-mib which should be available by tomorrow, but everything else that I could find as being available from the vendor docs is already included.  

As far as I can tell that profile covers everything in your request except memory util, but I cannot find an OID in your walk that displays current memory usage, just OID's that describe the memory modules that are installed without reference to utilization.  If you can point me to a specific OID that shows up in your walk then we can add it.
