### ISSUE TITLE
[Missing SNMP Polling Profile] D-Link DGS-3130-30TS System

### ISSUE THREAD

**Issue by wuetz** [kentik/snmp-profiles#665]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: D-Link

Device Model: D-Link DGS-3130-30TS System

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): OID: .1.3.6.1.4.1.171.10.154.1.2

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

- Interfaces use, link status, statistics etc
- TCP/IP Stack: Errors, Datadrops, etc
- Template fixes
 
Gist Link: https://gist.github.com/wuetz/6b278fddd79bd1ca31fe21b05f3193f8

**Comment by Mesverrum** [comment]
I apologize for the delayed response, there has been a change with the way SNMP profiles are handled.  In the interest of not being a bottleneck, SNMP profiles are now to be handled as a self-service item for users of ktranslate.  Your organization should fork this repo or copy the contents and make any desired changes directly there, you can see an example of how to pass a modified fork of the profile definitions in [this documentation](https://docs.newrelic.com/docs/network-performance-monitoring/advanced/snmp-profiles/).  You can find documentation of the syntax and capabilities of the profile definitions in this [template](https://github.com/kentik/snmp-profiles/blob/main/profiles/kentik_snmp/_template.yml).
There will be no need for approvals or review except those you implement within your own fork for yourselves.
