### ISSUE TITLE
Support for CyberArk Vault Server SNMP profile

### ISSUE THREAD

**Issue by larbib** [kentik/snmp-profiles#672]
Hi there

Could you consider providing support Support for CyberArk Vault Server SNMP profile?

SNMP MIBs are attached.

[CYBER-ARK-MIB-V1.txt](https://github.com/kentik/snmp-profiles/files/11621692/CYBER-ARK-MIB-V1.txt)
[CYBER-ARK-MIB-V2.txt](https://github.com/kentik/snmp-profiles/files/11621693/CYBER-ARK-MIB-V2.txt)

Thanks!
Larbi B.

**Comment by Mesverrum** [comment]
I apologize for the delayed response, there has been a change with the way SNMP profiles are handled.  In the interest of not being a bottleneck, SNMP profiles are now to be handled as a self-service item for users of ktranslate.  Your organization should fork this repo or copy the contents and make any desired changes directly there, you can see an example of how to pass a modified fork of the profile definitions in [this documentation](https://docs.newrelic.com/docs/network-performance-monitoring/advanced/snmp-profiles/).  You can find documentation of the syntax and capabilities of the profile definitions in this [template](https://github.com/kentik/snmp-profiles/blob/main/profiles/kentik_snmp/_template.yml).
There will be no need for approvals or review except those you implement within your own fork for yourselves.
