### ISSUE TITLE
[Adding SNMP Polling MIB Profile] - Cisco WLC model

### ISSUE THREAD

**Issue by cnuamrutha** [kentik/snmp-profiles#673]
Device Vendor: Cisco

Device Model: AIR-CT2504-K9

System Object Identifier (SysOID):

AIR-CT2504-K9 ------> SNMPv2-MIB::sysObjectID.0 = OID: 1.3.6.1.4.1.9.1.1279

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

MIB : https://software.cisco.com/download/home/283848165/type/280775088/release/8.0

    cldcClientUsername
    cldcClientDeviceType
    cldcClientMacAddress
    cldcClientIPAddress
    cldcClientAuthentication
    cldcClientChannel
    cldcClientSSID
    Access point Summary
    Top WLANS
    Client Summary
    

If there is a New Relic technical support case related to this request, please provide the case number: Case #00122808

**Comment by Mesverrum** [comment]
There has been a change with the way SNMP profiles are handled.  In the interest of not being a bottleneck, SNMP profiles are now to be handled as a self-service item for users of ktranslate.  Your organization should fork this repo or copy the contents and make any desired changes directly there, you can see an example of how to pass a modified fork of the profile definitions in [this documentation](https://docs.newrelic.com/docs/network-performance-monitoring/advanced/snmp-profiles/).  You can find documentation of the syntax and capabilities of the profile definitions in this [template](https://github.com/kentik/snmp-profiles/blob/main/profiles/kentik_snmp/_template.yml).
There will be no need for approvals or review except those you implement within your own fork for yourselves.
