### ISSUE TITLE
Cisco C8300 Profiles

### ISSUE THREAD

**Issue by bhatti4says** [kentik/snmp-profiles#676]
**Hi Team, Please add new profiles for latest cisco Serivce edge devices e.g. C8300.** 
Similarly C2960x is very old switch model, it's still not added. 

`KTranslate Cannot get device metadata on 192.168.18.50: request timeout (after 0 retries). Check for correct snmp credentials.
June 21, 2023 10:55:23
KTranslate Cannot get device metadata on 192.168.18.50: request timeout (after 0 retries). Check for correct snmp credentials.
June 21, 2023 10:55:20
KTranslate Profile for 1.3.6.1.4.1.9.1.2663 already exists. New file cisco-firepower-asa.yml, Old file cisco-asa.yml
June 21, 2023 10:55:20
KTranslate Profile for 1.3.6.1.4.1.9.1.2663 already exists. New file cisco-firepower-asa.yml, Old file cisco-asa.yml`

**Comment by bhatti4says** [comment]
Hi Team, we're a new bee here using NewRelic, it's been a week and we're struggling to monitor some of our Cisco Router ISE devices. Anyone has better suggestion please let me know. 

Thanks in advance.

**Comment by i3149** [comment]
Hi, 

Unfortunately, this project is unsupported going forwards. If you are interested in monitoring these devices with assistance, please contact sales@kentik.com to start a free Kentik trial. 

Best,

Ian
