### ISSUE TITLE
Profile for Draytek Vigor 2830v2

### ISSUE THREAD

**Issue by wootty2000** [kentik/snmp-profiles#690]
Draytek Vigor 2830v2

[snmpwalk.txt](https://github.com/kentik/snmp-profiles/files/12068596/snmpwalk.txt)

**Comment by Mesverrum** [comment]
@wootty2000 please see the [readme](https://github.com/kentik/snmp-profiles/blob/main/README.md), we are no longer able to create profiles on behalf of users.  You can refer to the documentation [tutorial](https://github.com/kentik/ktranslate/wiki/Tutorial:-Writing-a-custom-yaml-file-for-SNMP) and see these [examples](https://github.com/kentik/snmp-profiles/blob/main/profiles/kentik_snmp/_template.yml) to create your own profile and submit that as a pull request to be merged.
