### ISSUE TITLE
MIB for Mikrotik

### ISSUE THREAD

**Issue by iot-elite** [kentik/snmp-profiles#7]
I am not sure how to do this, but can a profile for Mikrotik be added?

The MIB file is attached.

Thanks,
Bogdan.
[Mikrotik.zip](https://github.com/kentik/snmp-profiles/files/7092460/Mikrotik.zip)

**Comment by i3149** [comment]
See #9, @iot-elite , what do you think? Are there metrics which you don't think are needed?

**Comment by iot-elite** [comment]
@i3149 I'm not sure what is the impact of keeping everything. I don't have specific needs for this, so I think including as much data as possible and filtering it in NewRelic would be an acceptable option?
