### ISSUE TITLE
HP Aruba JL256A profile is missing

### ISSUE THREAD

**Issue by pvadhyaphal** [kentik/snmp-profiles#71]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: Aruba (HP)

Device Model: Aruba JL256A 2930F-48G-PoE+-4SFP+ Switch

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): 1.3.6.1.4.1.11.2.3.7.11.181.21

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - IF-MIB
 - IP-MIB
 - OSPF-MIB
 - TCP-MIB
 - UDP-MIB
 - 
**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: https://gist.github.com/pvadhyaphal/980b40c54695a5accea7533ead9e07d7

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by Mesverrum** [comment]
Thanks, we have this in queue to build a profile for the device.  After the issue gets closed you will want to pull the newest image and rediscover the aruba devices.
