### ISSUE TITLE
Axis Camera SNMP Profile request

### ISSUE THREAD

**Issue by JimenezSP** [kentik/snmp-profiles#712]
Hello,

May someone point me in the right direction to build a SNMP profile for AXIS camera?

I have Three Models the Q1700, Q3536, P3265.

Any help will go a long way.

**Comment by thezackm** [comment]
hi there @JimenezSP ; thanks for your questions.

I would start with [this documentation](https://docs.newrelic.com/docs/network-performance-monitoring/advanced/snmp-profiles/) and then take a glance at a few of the basic SNMP profiles that are already in the repo (including the [_template.yml](https://github.com/kentik/snmp-profiles/blob/main/profiles/kentik_snmp/_template.yml) which outlines all of the available options).

the basic process is to get an SNMP walk from a target device and then break that down into the metrics you need to collect; then build a profile to match.

If you submit a PR, we'll be more than happy to iterate on anything in there with you.
