### ISSUE TITLE
ktranslate can't pull Velocloud MIBs 

### ISSUE THREAD

**Issue by Mamoon-Khan** [kentik/snmp-profiles#724]
Hi Team,

Couple week ago we updated the Velocloud SNMP profile (velocloud-edge.yml) with new MIBs and using it for our infrastructure. out of those new MIBs Ktranslate is not pulling 3 MIBs. Can you please look into this and guide us further. MIBs list is as below.

metric_tags:
      - column:   
          name: vceLinkName
          OID: 1.3.6.1.4.1.45346.1.1.2.3.2.2.1.3
      - column:     
          name: vcePathPeerName
          OID: 1.3.6.1.4.1.45346.1.1.2.4.2.2.1.6
      - column:    
          name: vceLinkItf
          OID: 1.3.6.1.4.1.45346.1.1.2.3.2.2.1.33

Thanks

**Comment by thezackm** [comment]
there's nothing in the YAML that looks off from a glance; can you confirm your device responds to these particular OIDs via an `snmpwalk` command? 

Additionally, remember that `metric_tags` are decorations on other metrics. Meaning that they are queried as a facet to one of your dimensional metrics.

```sql
FROM Metric SELECT
  latest(vceLinkState) AS 'Current State' -- Note enumerated metrics have their string values as a decoration too
  ,latest(kentik.snmp.vceLinkTxLatency) AS 'TX Latency'
  ,latest(kentik.snmp.vceLinkRxLatency) AS 'RX Latency'
FACET
  device_name
  ,vceLinkItf
  ,vceLinkName
  ,vcePathPeerName
SINCE 1 HOUR AGO
LIMIT 100
```

**Comment by Mamoon-Khan** [comment]
Hi Team,

Thanks for the information, this help us lot to resolve our issue.

Regards
Mamoon Ahmed

**Comment by thezackm** [comment]
happy to help; thanks!
