### ISSUE TITLE
[Missing SNMP Profile] Nasuni Filer

### ISSUE THREAD

**Issue by cbaroudi** [kentik/snmp-profiles#73]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: Nasuni  (www.nasuni.com)

Device Model: Cloud filer (file storage)

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): 
    Please note output from snmpwalk.
[NASUNI-FILER-MIB.txt](https://github.com/kentik/snmp-profiles/files/7557977/NASUNI-FILER-MIB.txt)
[NASUNI-FILER-MIB.txt](https://github.com/kentik/snmp-profiles/files/7557981/NASUNI-FILER-MIB.txt)

    
    
List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

    Attached is a MIB file from Nasuni.

 - 
 -
 -

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: 

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

    **Output from snmpwalk command:**
    
    # snmpwalk  -v2c -c pnmacsnmpmgt 10.117.120.83|grep OID
    iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.42040.1.1.0
    iso.3.6.1.2.1.1.9.1.2.1 = OID: iso.3.6.1.6.3.11.3.1.1
    iso.3.6.1.2.1.1.9.1.2.2 = OID: iso.3.6.1.6.3.15.2.1.1
    iso.3.6.1.2.1.1.9.1.2.3 = OID: iso.3.6.1.6.3.10.3.1.1
    iso.3.6.1.2.1.1.9.1.2.4 = OID: iso.3.6.1.6.3.1
    iso.3.6.1.2.1.1.9.1.2.5 = OID: iso.3.6.1.2.1.49
    iso.3.6.1.2.1.1.9.1.2.6 = OID: iso.3.6.1.2.1.4
    iso.3.6.1.2.1.1.9.1.2.7 = OID: iso.3.6.1.2.1.50
    iso.3.6.1.2.1.1.9.1.2.8 = OID: iso.3.6.1.6.3.16.2.2.1
    iso.3.6.1.2.1.1.9.1.2.9 = OID: iso.3.6.1.6.3.13.3.1.3
    iso.3.6.1.2.1.1.9.1.2.10 = OID: iso.3.6.1.2.1.92
    iso.3.6.1.2.1.2.2.1.22.1 = OID: ccitt.0
    iso.3.6.1.2.1.2.2.1.22.2 = OID: ccitt.0
    iso.3.6.1.2.1.2.2.1.22.3 = OID: ccitt.0
    

```

**Comment by Mesverrum** [comment]
Please send a gist link to an actual walk of a nasuni filer, we do not just use the MIBs to build profiles, which is why we don't ask for a MIB.

**Comment by cbaroudi** [comment]
Hi Marc,
I am not sure what you mean. I did provide output from the snmpwalk with the actual command I used. Please clarify.

**Comment by Mesverrum** [comment]
Not sure why you added the ' |grep OID' to the walk, that filtered out basically everything we wanted to get.  If you can run the command without that we should have what we need

**Comment by cbaroudi** [comment]
OK gotcha. I was trying to get the OID as requested in the form. Here is the full output. I didn't realize I was still filtering.

 # snmpwalk  -v2c -c pnmacsnmpmgt 10.117.120.83
 
iso.3.6.1.2.1.1.1.0 = STRING: "awlvprofilesp01 - VDI Profiles"
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.42040.1.1.0
iso.3.6.1.2.1.1.3.0 = Timeticks: (335136313) 38 days, 18:56:03.13
iso.3.6.1.2.1.1.4.0 = STRING: "Windows"
iso.3.6.1.2.1.1.5.0 = STRING: "awlvprofilesp01.pnmac.com"
iso.3.6.1.2.1.1.6.0 = STRING: "AWS"
iso.3.6.1.2.1.1.7.0 = INTEGER: 72
iso.3.6.1.2.1.1.8.0 = Timeticks: (3) 0:00:00.03
iso.3.6.1.2.1.1.9.1.2.1 = OID: iso.3.6.1.6.3.11.3.1.1
iso.3.6.1.2.1.1.9.1.2.2 = OID: iso.3.6.1.6.3.15.2.1.1
iso.3.6.1.2.1.1.9.1.2.3 = OID: iso.3.6.1.6.3.10.3.1.1
iso.3.6.1.2.1.1.9.1.2.4 = OID: iso.3.6.1.6.3.1
iso.3.6.1.2.1.1.9.1.2.5 = OID: iso.3.6.1.2.1.49
iso.3.6.1.2.1.1.9.1.2.6 = OID: iso.3.6.1.2.1.4
iso.3.6.1.2.1.1.9.1.2.7 = OID: iso.3.6.1.2.1.50
iso.3.6.1.2.1.1.9.1.2.8 = OID: iso.3.6.1.6.3.16.2.2.1
iso.3.6.1.2.1.1.9.1.2.9 = OID: iso.3.6.1.6.3.13.3.1.3
iso.3.6.1.2.1.1.9.1.2.10 = OID: iso.3.6.1.2.1.92
iso.3.6.1.2.1.1.9.1.3.1 = STRING: "The MIB for Message Processing and Dispatching."
iso.3.6.1.2.1.1.9.1.3.2 = STRING: "The management information definitions for the SNMP User-based Security Model."
iso.3.6.1.2.1.1.9.1.3.3 = STRING: "The SNMP Management Architecture MIB."
iso.3.6.1.2.1.1.9.1.3.4 = STRING: "The MIB module for SNMPv2 entities"
iso.3.6.1.2.1.1.9.1.3.5 = STRING: "The MIB module for managing TCP implementations"
iso.3.6.1.2.1.1.9.1.3.6 = STRING: "The MIB module for managing IP and ICMP implementations"
iso.3.6.1.2.1.1.9.1.3.7 = STRING: "The MIB module for managing UDP implementations"
iso.3.6.1.2.1.1.9.1.3.8 = STRING: "View-based Access Control Model for SNMP."
iso.3.6.1.2.1.1.9.1.3.9 = STRING: "The MIB modules for managing SNMP Notification, plus filtering."
iso.3.6.1.2.1.1.9.1.3.10 = STRING: "The MIB module for logging SNMP Notifications."
iso.3.6.1.2.1.1.9.1.4.1 = Timeticks: (3) 0:00:00.03
iso.3.6.1.2.1.1.9.1.4.2 = Timeticks: (3) 0:00:00.03
iso.3.6.1.2.1.1.9.1.4.3 = Timeticks: (3) 0:00:00.03
iso.3.6.1.2.1.1.9.1.4.4 = Timeticks: (3) 0:00:00.03
iso.3.6.1.2.1.1.9.1.4.5 = Timeticks: (3) 0:00:00.03
iso.3.6.1.2.1.1.9.1.4.6 = Timeticks: (3) 0:00:00.03
iso.3.6.1.2.1.1.9.1.4.7 = Timeticks: (3) 0:00:00.03
iso.3.6.1.2.1.1.9.1.4.8 = Timeticks: (3) 0:00:00.03
iso.3.6.1.2.1.1.9.1.4.9 = Timeticks: (3) 0:00:00.03
iso.3.6.1.2.1.1.9.1.4.10 = Timeticks: (3) 0:00:00.03
iso.3.6.1.2.1.2.1.0 = INTEGER: 3
iso.3.6.1.2.1.2.2.1.1.1 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.1.2 = INTEGER: 2
iso.3.6.1.2.1.2.2.1.1.3 = INTEGER: 3
iso.3.6.1.2.1.2.2.1.2.1 = STRING: "lo"
iso.3.6.1.2.1.2.2.1.2.2 = STRING: "eth0"
iso.3.6.1.2.1.2.2.1.2.3 = STRING: "ifb0"
iso.3.6.1.2.1.2.2.1.3.1 = INTEGER: 24
iso.3.6.1.2.1.2.2.1.3.2 = INTEGER: 6
iso.3.6.1.2.1.2.2.1.3.3 = INTEGER: 6
iso.3.6.1.2.1.2.2.1.4.1 = INTEGER: 65536
iso.3.6.1.2.1.2.2.1.4.2 = INTEGER: 9001
iso.3.6.1.2.1.2.2.1.4.3 = INTEGER: 1500
iso.3.6.1.2.1.2.2.1.5.1 = Gauge32: 10000000
iso.3.6.1.2.1.2.2.1.5.2 = Gauge32: 0
iso.3.6.1.2.1.2.2.1.5.3 = Gauge32: 0
iso.3.6.1.2.1.2.2.1.6.1 = ""
iso.3.6.1.2.1.2.2.1.6.2 = Hex-STRING: 06 7C 95 41 50 4D
iso.3.6.1.2.1.2.2.1.6.3 = Hex-STRING: 26 D8 D7 23 38 67
iso.3.6.1.2.1.2.2.1.7.1 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.7.2 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.7.3 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.8.1 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.8.2 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.8.3 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.9.1 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.2.2.1.9.2 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.2.2.1.9.3 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.2.2.1.10.1 = Counter32: 2010218345
iso.3.6.1.2.1.2.2.1.10.2 = Counter32: 1676061629
iso.3.6.1.2.1.2.2.1.10.3 = Counter32: 1012273720
iso.3.6.1.2.1.2.2.1.11.1 = Counter32: 283957400
iso.3.6.1.2.1.2.2.1.11.2 = Counter32: 1739003904
iso.3.6.1.2.1.2.2.1.11.3 = Counter32: 3006849237
iso.3.6.1.2.1.2.2.1.12.1 = Counter32: 0
iso.3.6.1.2.1.2.2.1.12.2 = Counter32: 0
iso.3.6.1.2.1.2.2.1.12.3 = Counter32: 0
iso.3.6.1.2.1.2.2.1.13.1 = Counter32: 0
iso.3.6.1.2.1.2.2.1.13.2 = Counter32: 20034
iso.3.6.1.2.1.2.2.1.13.3 = Counter32: 3
iso.3.6.1.2.1.2.2.1.14.1 = Counter32: 0
iso.3.6.1.2.1.2.2.1.14.2 = Counter32: 0
iso.3.6.1.2.1.2.2.1.14.3 = Counter32: 0
iso.3.6.1.2.1.2.2.1.15.1 = Counter32: 0
iso.3.6.1.2.1.2.2.1.15.2 = Counter32: 0
iso.3.6.1.2.1.2.2.1.15.3 = Counter32: 0
iso.3.6.1.2.1.2.2.1.16.1 = Counter32: 2010218345
iso.3.6.1.2.1.2.2.1.16.2 = Counter32: 3915693114
iso.3.6.1.2.1.2.2.1.16.3 = Counter32: 1012273510
iso.3.6.1.2.1.2.2.1.17.1 = Counter32: 283957400
iso.3.6.1.2.1.2.2.1.17.2 = Counter32: 157486522
iso.3.6.1.2.1.2.2.1.17.3 = Counter32: 3006849234
iso.3.6.1.2.1.2.2.1.18.1 = Counter32: 0
iso.3.6.1.2.1.2.2.1.18.2 = Counter32: 0
iso.3.6.1.2.1.2.2.1.18.3 = Counter32: 0
iso.3.6.1.2.1.2.2.1.19.1 = Counter32: 0
iso.3.6.1.2.1.2.2.1.19.2 = Counter32: 0
iso.3.6.1.2.1.2.2.1.19.3 = Counter32: 0
iso.3.6.1.2.1.2.2.1.20.1 = Counter32: 0
iso.3.6.1.2.1.2.2.1.20.2 = Counter32: 0
iso.3.6.1.2.1.2.2.1.20.3 = Counter32: 0
iso.3.6.1.2.1.2.2.1.21.1 = Gauge32: 0
iso.3.6.1.2.1.2.2.1.21.2 = Gauge32: 0
iso.3.6.1.2.1.2.2.1.21.3 = Gauge32: 0
iso.3.6.1.2.1.2.2.1.22.1 = OID: ccitt.0
iso.3.6.1.2.1.2.2.1.22.2 = OID: ccitt.0
iso.3.6.1.2.1.2.2.1.22.3 = OID: ccitt.0
iso.3.6.1.2.1.25.1.1.0 = Timeticks: (335139011) 38 days, 18:56:30.11
iso.3.6.1.2.1.25.1.2.0 = Hex-STRING: 07 E5 0B 11 0F 01 30 00 2D 08 00
iso.3.6.1.2.1.25.1.3.0 = INTEGER: 393216
iso.3.6.1.2.1.25.1.4.0 = STRING: "BOOT_IMAGE=/vmlinuz-3.10.0-1160.24.1.el7.x86_64 root=/dev/filer/root ro pci=bfsort selinux=0 consoleblank=0 logo.nologo mds=off "
iso.3.6.1.2.1.25.1.5.0 = Gauge32: 0
iso.3.6.1.2.1.25.1.6.0 = Gauge32: 1926
iso.3.6.1.2.1.25.1.7.0 = INTEGER: 0
iso.3.6.1.2.1.31.1.1.1.1.1 = STRING: "lo"
iso.3.6.1.2.1.31.1.1.1.1.2 = STRING: "eth0"
iso.3.6.1.2.1.31.1.1.1.1.3 = STRING: "ifb0"
iso.3.6.1.2.1.31.1.1.1.2.1 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.2.2 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.2.3 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.3.1 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.3.2 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.3.3 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.4.1 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.4.2 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.4.3 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.5.1 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.5.2 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.5.3 = Counter32: 0
iso.3.6.1.2.1.31.1.1.1.6.1 = Counter64: 117974335337
iso.3.6.1.2.1.31.1.1.1.6.2 = Counter64: 5567953677245
iso.3.6.1.2.1.31.1.1.1.6.3 = Counter64: 4592332313144
iso.3.6.1.2.1.31.1.1.1.7.1 = Counter64: 283957400
iso.3.6.1.2.1.31.1.1.1.7.2 = Counter64: 6033971200
iso.3.6.1.2.1.31.1.1.1.7.3 = Counter64: 3006849237
iso.3.6.1.2.1.31.1.1.1.8.1 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.8.2 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.8.3 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.9.1 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.9.2 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.9.3 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.10.1 = Counter64: 117974335337
iso.3.6.1.2.1.31.1.1.1.10.2 = Counter64: 10367671778362
iso.3.6.1.2.1.31.1.1.1.10.3 = Counter64: 4592332312934
iso.3.6.1.2.1.31.1.1.1.11.1 = Counter64: 283957400
iso.3.6.1.2.1.31.1.1.1.11.2 = Counter64: 8747421114
iso.3.6.1.2.1.31.1.1.1.11.3 = Counter64: 3006849234
iso.3.6.1.2.1.31.1.1.1.12.1 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.12.2 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.12.3 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.13.1 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.13.2 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.13.3 = Counter64: 0
iso.3.6.1.2.1.31.1.1.1.15.1 = Gauge32: 10
iso.3.6.1.2.1.31.1.1.1.15.2 = Gauge32: 0
iso.3.6.1.2.1.31.1.1.1.15.3 = Gauge32: 0
iso.3.6.1.2.1.31.1.1.1.16.1 = INTEGER: 2
iso.3.6.1.2.1.31.1.1.1.16.2 = INTEGER: 2
iso.3.6.1.2.1.31.1.1.1.16.3 = INTEGER: 2
iso.3.6.1.2.1.31.1.1.1.17.1 = INTEGER: 2
iso.3.6.1.2.1.31.1.1.1.17.2 = INTEGER: 1
iso.3.6.1.2.1.31.1.1.1.17.3 = INTEGER: 1
iso.3.6.1.2.1.31.1.1.1.18.1 = ""
iso.3.6.1.2.1.31.1.1.1.18.2 = ""
iso.3.6.1.2.1.31.1.1.1.18.3 = ""
iso.3.6.1.2.1.31.1.1.1.19.1 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.31.1.1.1.19.2 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.31.1.1.1.19.3 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.31.1.5.0 = Timeticks: (0) 0:00:00.00

**Comment by cbaroudi** [comment]
I generated the snmpwalk using the command provided and placed it here:  https://gist.github.com/cbaroudi/e15a2a671d86a2e3591cd2bbbb62a622

Thanks.

**Comment by cbaroudi** [comment]
Hi,
Following up to find out if you have all that you need to proceed with this request.
Please let me know. 

Thank you.
Regards, Chris

**Comment by Mesverrum** [comment]
Yes thank you, we will get it in queue for a profile to be built, once this issue is closed you will want to pull the latest image and re-discover these devices and you should be set
