### ISSUE TITLE
[Missing SNMP Polling Profile] FAD300F

### ISSUE THREAD

**Issue by MuugiiN** [kentik/snmp-profiles#740]
Device Vendor:  FORTINET
Device Model: FAD300F
System Object Identifier (SysOID): 1.3.6.1.4.1.12356.112.100.303
Case #00125254

**Comment by thezackm** [comment]
@MuugiiN - please submit a pull request with your proposed changes for review. you can find directions in the [New Relic docs](https://docs.newrelic.com/docs/network-performance-monitoring/advanced/snmp-profiles/#snmp-polling)
