### ISSUE TITLE
Use name: cLWlanSsid for 9800 WLCs

### ISSUE THREAD

**Issue by aditdeshpande10** [kentik/snmp-profiles#779]
profiles/kentik_snmp/cisco/cisco-wlc.yml

- column:
          name: cLWlanSsid
          OID: 1.3.6.1.4.1.9.9.512.1.1.1.1.4
        tag: wlan_ssid
lines 203-206

Can this metric be used for 9800 WLCs to display the SSID Name instead of bsnDot11EssSsid since the OID (1.3.6.1.4.1.14179.2.1.1.1.2) is unavailable on the 9800 WLCs?  

I have attached a screenshot of a Air OS WLC and 9800 WLC for reference.
![Screenshot 2024-05-30 at 5 59 32 PM](https://github.com/kentik/snmp-profiles/assets/110008516/02bd34c6-823f-4ac9-ab44-c54ba7067767)
![Screenshot 2024-05-31 at 12 46 35 PM](https://github.com/kentik/snmp-profiles/assets/110008516/b24e7770-3fc0-45d1-8720-7f5010dcd329)

[user@host ~]$ snmpwalk -v3 -l authPriv -u user -a <> -A <> -x <> -X <> hyd1-wlc-a 1.3.6.1.4.1.9.9.512.1.1.1.1.4
SNMPv2-SMI::enterprises.9.9.512.1.1.1.1.4.11 = STRING: "GoMobile"
SNMPv2-SMI::enterprises.9.9.512.1.1.1.1.4.12 = STRING: "SalesforceGuest"
SNMPv2-SMI::enterprises.9.9.512.1.1.1.1.4.13 = STRING: "Mirror"

**Comment by thezackm** [comment]
@aditdeshpande10 - thanks for the issue

can you validate that the index value of the 2 tables is aligned as expected? this would be the "join" between them that could enable your request.

[cLWlanConfigTable:cLWlanIndex](https://mibs.observium.org/mib/CISCO-LWAPP-WLAN-MIB/#cLWlanIndex)
```
snmpwalk -v 3 -l $LEVEL -u $USERNAME -a $AUTH_PROTOCOL -A $AUTH_PASSPHRASE -x $PRIV_PROTOCOL -X $PRIV_PASSPHRASE -ObentU -Cc $IP_ADDRESS .1.3.6.1.4.1.9.9.512.1.1.1
```

[bsnDot11EssTable:bsnDot11EssIndex](https://mibs.observium.org/mib/AIRESPACE-WIRELESS-MIB/#bsnDot11EssIndex)
```
snmpwalk -v 3 -l $LEVEL -u $USERNAME -a $AUTH_PROTOCOL -A $AUTH_PASSPHRASE -x $PRIV_PROTOCOL -X $PRIV_PASSPHRASE -ObentU -Cc $IP_ADDRESS .1.3.6.1.4.1.14179.2.1.1
```

The idea being that adding `CISCO-LWAPP-WLAN-MIB::cLWlanConfigTable::cLWlanSsid` as a metric tag decoration on the `AIRESPACE-WIRELESS-MIB::bsnDot11EssTable::bsnDot11EssSsid` will only work if the Index value from the 2 different MIB tables is identical. Otherwise there won't be a way to understand which value from one MIB aligns to the other.

**Comment by aditdeshpande10** [comment]
@thezackm Thanks for the feedback. The index values are same for both the MIBs. However, the objects in the 2 tables are completely different. I'm attaching a screenshot of the index values - 1 is from a Air OS WLC ([cLWlanIndex]and the other is from a IOS-XE (9800 series WLC) [bsnDot11EssTable:bsnDot11EssIndex]

SNMPwalk-
1.  cLWlanSsid: 
 snmpwalk -v3 -l <> -u <> -a <> -A <> -x <> -X <> <AirOS WLC> .1.3.6.1.4.1.9.9.512.1.1.1
SNMPv2-SMI::enterprises.9.9.512.1.1.1.1.2.11 = INTEGER: 1
SNMPv2-SMI::enterprises.9.9.512.1.1.1.1.2.12 = INTEGER: 1
SNMPv2-SMI::enterprises.9.9.512.1.1.1.1.2.13 = INTEGER: 1
SNMPv2-SMI::enterprises.9.9.512.1.1.1.1.3.11 = STRING: "GoMobile"
SNMPv2-SMI::enterprises.9.9.512.1.1.1.1.3.12 = STRING: "Salesforce Guest"
SNMPv2-SMI::enterprises.9.9.512.1.1.1.1.3.13 = STRING: "Mirror"
SNMPv2-SMI::enterprises.9.9.512.1.1.1.1.4.11 = STRING: "GoMobile"
SNMPv2-SMI::enterprises.9.9.512.1.1.1.1.4.12 = STRING: "SalesforceGuest"
SNMPv2-SMI::enterprises.9.9.512.1.1.1.1.4.13 = STRING: "Mirror"

 snmpwalk -v3 -l <> -u <> -a <> -A <> -x <> -X <> <IOS-XE WLC> .1.3.6.1.4.1.9.9.512.1.1.1 .1.3.6.1.4.1.9.9.512.1.1.1
SNMPv2-SMI::enterprises.9.9.512.1.1.1.1.2.11 = INTEGER: 1
SNMPv2-SMI::enterprises.9.9.512.1.1.1.1.2.12 = INTEGER: 1
SNMPv2-SMI::enterprises.9.9.512.1.1.1.1.2.13 = INTEGER: 1
SNMPv2-SMI::enterprises.9.9.512.1.1.1.1.3.11 = STRING: "GoMobile"
SNMPv2-SMI::enterprises.9.9.512.1.1.1.1.3.12 = STRING: "SalesforceGuest"
SNMPv2-SMI::enterprises.9.9.512.1.1.1.1.3.13 = STRING: "Mirror"
SNMPv2-SMI::enterprises.9.9.512.1.1.1.1.4.11 = STRING: "GoMobile"
SNMPv2-SMI::enterprises.9.9.512.1.1.1.1.4.12 = STRING: "SalesforceGuest"
SNMPv2-SMI::enterprises.9.9.512.1.1.1.1.4.13 = STRING: "Mirror"

2. bsnDot11EssSsid:
snmpwalk -v3 -l <> -u <> -a <> -A <> -x <> -X <> <IOS-XE WLC> .1.3.6.1.4.1.14179.2.1.1
SNMPv2-SMI::enterprises.14179.2.1.1.1.1.11 = Gauge32: 11
SNMPv2-SMI::enterprises.14179.2.1.1.1.1.12 = Gauge32: 12
SNMPv2-SMI::enterprises.14179.2.1.1.1.1.13 = Gauge32: 13
SNMPv2-SMI::enterprises.14179.2.1.1.1.5.11 = INTEGER: 1
SNMPv2-SMI::enterprises.14179.2.1.1.1.5.12 = INTEGER: 1
SNMPv2-SMI::enterprises.14179.2.1.1.1.5.13 = INTEGER: 1
SNMPv2-SMI::enterprises.14179.2.1.1.1.6.11 = INTEGER: 1
SNMPv2-SMI::enterprises.14179.2.1.1.1.6.12 = INTEGER: 1
SNMPv2-SMI::enterprises.14179.2.1.1.1.6.13 = INTEGER: 1

snmpwalk -v3 -l <> -u <> -a <> -A <> -x <> -X <> <Air OS WLC> .1.3.6.1.4.1.14179.2.1.1
SNMPv2-SMI::enterprises.14179.2.1.1.1.1.11 = Gauge32: 11
SNMPv2-SMI::enterprises.14179.2.1.1.1.1.12 = Gauge32: 12
SNMPv2-SMI::enterprises.14179.2.1.1.1.1.13 = Gauge32: 13
SNMPv2-SMI::enterprises.14179.2.1.1.1.2.11 = STRING: "GoMobile"
SNMPv2-SMI::enterprises.14179.2.1.1.1.2.12 = STRING: "SalesforceGuest"
SNMPv2-SMI::enterprises.14179.2.1.1.1.2.13 = STRING: "Mirror"
<img width="803" alt="Screenshot 2024-06-10 at 10 35 30 AM" src="https://github.com/kentik/snmp-profiles/assets/110008516/0291d4f2-9550-4267-9eb9-75ba6026b1bd">
<img width="1571" alt="Screenshot 2024-06-10 at 10 36 17 AM" src="https://github.com/kentik/snmp-profiles/assets/110008516/27737550-39ac-4fe1-913b-ba833f64d510">

**Comment by thezackm** [comment]
I'm not sure I understand. Is the value from both MIBs looking at the same SSID or not? If not, then the vendor's MIB support doesn't extend to your needs. If it is, we can probably adjust this profile to make it work.

**Comment by aditdeshpande10** [comment]
Yes, the values are matching i.e. it's pointing to the same SSIDs. Should I proceed with a PR? I'll move the metrics tags (lines 196-206) to line 468 such that it's added as an extension to AIRESPACE-WIRELESS-MIB. Please advise if this is appropriate.

**Comment by thezackm** [comment]
correct; technically you'd copy, not move. we still want the original metric tag for lines [197-206](https://github.com/kentik/snmp-profiles/blob/63ca0bd240d8f003d1e13de6bbc9f6290ff7a960/profiles/kentik_snmp/cisco/cisco-wlc.yml#L197-L206) in place as well.

**Comment by aditdeshpande10** [comment]
@thezackm Thanks for confirming, please review the PR - https://github.com/kentik/snmp-profiles/pull/780 
Suggest changes, if any.

**Comment by aditdeshpande10** [comment]
Hi @thezackm I'm following up on the PR - https://github.com/kentik/snmp-profiles/pull/780 I submitted last week. Please let me know if any changes/modifications are required from my side.
