### ISSUE TITLE
[Missing SNMP Polling Profile]

### ISSUE THREAD

**Issue by GabrielMaestre** [kentik/snmp-profiles#783]
Device Vendor: VMware
Device Model: VMware ESXi 8.0.1 build-21495797 VMware, Inc. x86_64
System Object Identifier: .1.3.6.1.4.1.6876.4.1
`.1.3.6.1.2.1.1.2.0` = OID: .1.3.6.1.4.1.6876.4.1

Critical Metrics: We are using New Relic, but we only recive/found: CPU, Process Count, hrStorage Summary and hrStorage Used. Missing a lot of Metrics like Memory, Disk, Device details, and a lot more.

Gist Link: https://gist.github.com/GabrielMaestre/efbc7470841f00780150d16b91630c5b (snmpwalk & zabbix template metrics)
Mibs Used: VMWARE-ENV-MIB, VMWARE-RESOURCES-MIB

**Comment by thezackm** [comment]
@GabrielMaestre - [this is the current profile](https://github.com/kentik/snmp-profiles/blob/main/profiles/kentik_snmp/vmware/esx.yml) used for ESX hosts. Please submit a pull request with the metrics you'd like to add. Alternatively you have the option to [build and run your own versions of the profiles](https://docs.newrelic.com/docs/network-performance-monitoring/advanced/snmp-profiles/#private) as described in the documentation.

_Note that the preferred approach within New Relic is to use the [vSphere monitoring integration](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/vmware-vsphere-monitoring-integration/) which is purpose-built for this and a much better alternative to using SNMP._
