### ISSUE TITLE
Missing metrics #784

### ISSUE THREAD

**Issue by aditdeshpande10** [kentik/snmp-profiles#790]
@thezackm My PR  #784 was recently merged. It included 3 metrics from the CISCO-AUTH-FRAMEWORK-MIB. Ref - https://github.com/kentik/snmp-profiles/blob/c19a259debbe8a5f314dc5470e5eda1fc540cd0b/profiles/kentik_snmp/cisco/cisco-all-devices.yml#L1151

 However, I don't find these metrics in New Relic. I've verified that our docker image is v2.2.28 which is the latest image. On checking the commit history it looks like the one of the checks failed while pushing the code. Can you please try to again push the code?

**Comment by thezackm** [comment]
this was fixed in PR #788 as there were some YAML issues with the original merge. The current version of the container and RPM package have this fix already so if you're seeing issues you need to open a support case for further investigation.

**Comment by aditdeshpande10** [comment]
@thezackm I need to open a support case with New Relic for further investigation?

**Comment by aditdeshpande10** [comment]
That's our monitoring platform.

**Comment by thezackm** [comment]
Correct. They'll be able to help dig into the details and troubleshoot the issue with you further. That's not something that can be done here in GitHub and the support case will be the fastest path to resolution for you.

**Comment by jryburn** [comment]
This appears to be an issue with new profile submitted in PR #784.

These are working:
-  1.3.6.1.4.1.9.9.656.1.2.1.1.6 (kentik.snmp.cafPortReauthEnabled)
- 1.3.6.1.4.1.9.9.656.1.2.1.1.7 (kentik.snmp.cafPortReauthInterval)

But this one is not:
- 1.3.6.1.4.1.9.9.656.1.4.1.1.15 (kentik.snmp.cafSessionTimeout)

Customer SNMPWalk ([link](https://drive.google.com/file/d/1Fq-2JMAlQmhfRD5EDk9WVlOn-NYxGJd2/view?usp=sharing)) seems to show the data should be available. This is running against a Cisco L3 switch Catalyst 9300 running Version 17.9.3 OS.

It appears the YAML formatting for this OID is off. I'm going to attempt to fix it in a new PR shortly.
