### ISSUE TITLE
Ubiquiti Unifi AP CPU reports 100* actual 

### ISSUE THREAD

**Issue by MikeDembek** [kentik/snmp-profiles#800]
Hi, I'm seeing my Ubiquiti APs (U7 Pros running 7.0.59 firmware) reporting CPU values that are 100 times greater than actual.  For example, for an AP I just checked in my Unifi controller showing 1.1% CPU, I see this value in an snmpwalk:

.1.3.6.1.4.1.10002.1.1.1.4.2.1.3.1 = Gauge32: 108

That then translates to 108% in New Relic.

This seems to be a common issue with Unifi with 3rd party SNMP monitoring; could this get adjusted in the unifi-access-point.yml config?

**Comment by MikeDembek** [comment]
This issue is still outstanding

**Comment by i3149** [comment]
Can you submit a PR to fix this? This repo isn't currently maintained but we do accept outside pull requests. To fix, you'll want to do something like this example with [isolon](https://github.com/kentik/snmp-profiles/blob/main/profiles/kentik_snmp/isilon/isilon.yml):

```python
        # This script converts the per mil results into a proper percentage for CPU
        script: |
          def main(n):
            cpuim = n["CPU"]
            n["CPU"] = cpuim * 0.01
            return None
```

Note above is just an example, you'll need to test it to get it working for real.
