### ISSUE TITLE
C8500-12X Edge Router - Default Device

### ISSUE THREAD

**Issue by jonesmj14** [kentik/snmp-profiles#803]
Hi, I have added some C8500-12X Edge Routers to be monitored, but they are being discovered as Default Device rather than being seen as a Cisco ASR.   I believe the following needs to be added to the Cisco ASR profile

1.3.6.1.4.1.9.1.2819 # C8500-12X Edge Router

**Comment by i3149** [comment]
Can you submit this as a PR? We don't currently maintain this repo but do accept merge requests.
