### ISSUE TITLE
[Missing SNMP Polling Profile] case# 00235681

### ISSUE THREAD

**Issue by copypastepro** [kentik/snmp-profiles#820]
[sns.evo.walk.txt](https://github.com/user-attachments/files/17817830/sns.evo.walk.txt)

attached you will find the snmpwalk for 

SNS EVO server

https://www.studionetworksolutions.com/evo/shared-storage/?utm_term=evo%20sns&utm_campaign=Searching+for+EVO&utm_source=adwords&utm_medium=ppc&hsa_acc=9596576459&hsa_cam=56457964&hsa_grp=1626000274&hsa_ad=351122162567&hsa_src=g&hsa_tgt=kwd-17217960364&hsa_kw=evo%20sns&hsa_mt=b&hsa_net=adwords&hsa_ver=3&gad_source=1&gclid=Cj0KCQiAi_G5BhDXARIsAN5SX7rWRoSslwWy7WRXGFyC6Ym-ozPzUwpzqYSP8V4TXh59H1LO81l-pDcaAqZPEALw_wcB

**Comment by i3149** [comment]
We're not currently resourced to add profiles directly, but if you submit a PR with this device I'll be happy to review and add it.
